# DENTEX Final Model Runner

This notebook combines the strongest findings from the earlier experiments: lower learning rate training for Model A and Model B from the regularisation sweep, plus the separate YOLO11s quadrant detector from the Model C quadrant experiment. It trains on the official training split, selects and reports on validation, then evaluates the released test labels in the same style as `dentex.ipynb`.

## 1. Environment Setup

In [1]:
!pip install -q ultralytics==8.3.32 pandas==2.2.2 pycocotools==2.0.8 scipy==1.14.1 matplotlib==3.9.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.0/887.0 kB 17.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 83.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.5/443.5 kB 25.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 50.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 115.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.35.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.

In [2]:
import contextlib
import io
import json
import math
import os
import random
import shutil
import time
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from PIL import Image
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
from scipy.optimize import linear_sum_assignment
from ultralytics import YOLO

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

IS_KAGGLE = Path('/kaggle').exists()
BASE_WORK_ROOT = Path('/kaggle/working') if IS_KAGGLE else Path('.')
PROJECT_DIRNAME = 'dentex_final_model_c'

CFG = {
    'is_kaggle': IS_KAGGLE,
    'kaggle_dataset_url': 'https://www.kaggle.com/datasets/lemhui/dentex',
    'kaggle_dataset_root': Path('/kaggle/input/datasets/lemhui/dentex'),
    'work_root': BASE_WORK_ROOT / PROJECT_DIRNAME,
    'yolo_root': BASE_WORK_ROOT / PROJECT_DIRNAME / 'yolo',
    'runs_root': BASE_WORK_ROOT / PROJECT_DIRNAME / 'runs',
    'pred_root': BASE_WORK_ROOT / PROJECT_DIRNAME / 'predictions',
    'official_eval_root': BASE_WORK_ROOT / PROJECT_DIRNAME / 'official_eval',
    'pathology_class_names': [],
    'enumeration_class_names': [f'tooth_{i}' for i in range(1, 9)],
    'quadrant_class_names': [f'quadrant_{i}' for i in range(1, 5)],
    'imgsz': 1024,
    'epochs': 500,
    'sanity_mode': False,
    'sanity_epochs': 1,
    'sanity_fraction': 0.1,
    'sanity_imgsz': 640,
    'sanity_batch': 4,
    'sanity_max_eval_images': 24,
    'sanity_max_test_images': 40,
    'batch': 8,
    'patience': 30,
    'device': 0 if torch.cuda.is_available() else 'cpu',
    'workers': min(8, max(2, (os.cpu_count() or 4) // 2)),
    'cache': False,
    'optimizer': 'AdamW',
    'lr0': 0.003,
    'weight_decay': 0.0005,
    'mosaic': 0.1,
    'mixup': 0.0,
    'degrees': 8.0,
    'translate': 0.03,
    'scale': 0.15,
    'hsv_h': 0.01,
    'hsv_s': 0.15,
    'hsv_v': 0.15,
    'fliplr': 0.0,
    'flipud': 0.0,
    'pathology_conf': 0.15,
    'tooth_conf': 0.25,
    'quadrant_conf': 0.25,
    'predict_iou': 0.50,
    'ab_enable_tta': True,
    'quadrant_enable_tta': False,
    'tta_fusion_iou': 0.55,
    'prune_heavy_outputs': True,
}

FINAL_CONFIG = {
    'name': 'final_model_c_lower_lr_yolo11s_quadrant',
    'pathology_model': 'yolo11n.pt',
    'tooth_model': 'yolo11n.pt',
    'quadrant_model': 'yolo11s.pt',
    'imgsz': 1024,
    'epochs': 500,
    'patience': 30,
    'lr0': 0.003,
    'weight_decay': 0.0005,
    'mosaic': 0.1,
    'scale': 0.15,
    'degrees': 8.0,
    'ab_enable_tta': True,
    'quadrant_enable_tta': False,
    'tooth_assignment_mode': 'nearest',
    'quadrant_assignment_mode': 'nearest',
}

if CFG['sanity_mode']:
    CFG['epochs'] = CFG['sanity_epochs']
    CFG['patience'] = 1
    CFG['imgsz'] = CFG['sanity_imgsz']
    CFG['batch'] = CFG['sanity_batch']
    CFG['predict_iou'] = 0.4
    CFG['ab_enable_tta'] = False
    CFG['quadrant_enable_tta'] = False
    FINAL_CONFIG = dict(
        FINAL_CONFIG,
        imgsz=CFG['sanity_imgsz'],
        epochs=CFG['sanity_epochs'],
        ab_enable_tta=False,
        quadrant_enable_tta=False,
    )

for path_key in [
    'work_root',
    'yolo_root',
    'runs_root',
    'pred_root',
    'official_eval_root',
]:
    CFG[path_key].mkdir(parents=True, exist_ok=True)

print(f"Kaggle runtime: {CFG['is_kaggle']}")
print(f"Device: {CFG['device']}")
print(f"Workers: {CFG['workers']}")
print(f"Working root: {CFG['work_root']}")
print(f"Dataset URL: {CFG['kaggle_dataset_url']}")
print(f"Sanity mode: {CFG['sanity_mode']}")
print('Final configuration:')
print(json.dumps({k: str(v) for k, v in FINAL_CONFIG.items()}, indent=2))

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Kaggle runtime: True
Device: 0
Workers: 2
Working root: /kaggle/working/dentex_final_model_c
Dataset URL: https://www.kaggle.com/datasets/lemhui/dentex
Sanity mode: False
Final configuration:
{
  "name": "final_model_c_lower_lr_yolo11s_quadrant",
  "pathology_model": "yolo11n.pt",
  "tooth_model": "yolo11n.pt",
  "quadrant_model": "yolo11s.pt",
  "imgsz": "1024",
  "epochs": "500",
  "patience": "30",
  "lr0": "0.003",
  "weight_decay": "0.0005",
  "mosaic": "0.1",
  "scale": "0.15",
  "degrees": "8.0",
  "ab_enable_tta": "True",
  "quadrant_enable_tta": "False",
  "tooth_assignment_mode": "nearest",
  "quadrant_assignment_mode": "nearest"
}

## 2. Resolve Official DENTEX Splits From Kaggle Dataset

In [3]:
def resolve_kaggle_dataset_root() -> Path:
    dataset_root = CFG['kaggle_dataset_root']
    if not dataset_root.exists() or not dataset_root.is_dir():
        raise FileNotFoundError(
            f"Required dataset directory not found: {dataset_root}"
        )

    has_training = (dataset_root / 'training_data').exists()
    has_validation = (dataset_root / 'validation_data').exists()
    has_test = (dataset_root / 'test_data').exists()
    if not (has_training and has_validation and has_test):
        raise FileNotFoundError(
            f"Dataset directory exists but expected split folders are missing under: {dataset_root}"
        )

    return dataset_root


def json_candidates(root: Path) -> List[Path]:
    if not root.exists():
        return []
    return sorted(
        [path for path in root.rglob('*') if path.is_file() and path.suffix.lower() == '.json']
    )


def find_annotation_json(split_root: Path, split_name: str | None = None) -> Path:
    dataset_root = CFG['kaggle_dataset_root']

    def is_coco_json(path: Path) -> bool:
        try:
            with path.open('r', encoding='utf-8') as file:
                payload = json.load(file)
        except Exception:
            return False
        return isinstance(payload, dict) and {'images', 'annotations'}.issubset(payload.keys())

    split_jsons = json_candidates(split_root)
    split_coco = [path for path in split_jsons if is_coco_json(path)]

    if split_name == 'validation':
        validation_triple = dataset_root / 'validation_triple.json'
        if validation_triple.exists() and is_coco_json(validation_triple):
            return validation_triple
        raise FileNotFoundError(
            f'Validation COCO JSON not found at expected path: {validation_triple}'
        )

    if split_name == 'training':
        if split_coco:
            ranked = sorted(
                split_coco,
                key=lambda path: (
                    'quadrant-enumeration-disease' not in str(path).lower().replace('_', '-'),
                    len(str(path)),
                ),
            )
            return ranked[0]
        raise FileNotFoundError(
            f'No COCO-style training annotation JSON found inside split root: {split_root}'
        )

    if split_name == 'test':
        raise FileNotFoundError(
            'This Kaggle layout stores test labels as per-image LabelMe JSON files, not a single COCO annotation JSON.'
        )

    if split_name is None and split_coco:
        return split_coco[0]

    dataset_jsons = json_candidates(dataset_root) if dataset_root.exists() else []
    dataset_coco = [path for path in dataset_jsons if is_coco_json(path)]
    if dataset_coco:
        return dataset_coco[0]

    raise FileNotFoundError(
        f'No COCO-style annotation JSON found for split={split_name} under {split_root}'
    )


def find_image_root(annotation_path: Path, first_image_file: str, split_root: Path | None = None) -> Path:
    candidates = [
        annotation_path.parent / 'xrays',
        annotation_path.parent,
        annotation_path.parents[1] / 'xrays',
        annotation_path.parents[1],
    ]

    if split_root is not None:
        candidates.extend([
            split_root / 'xrays',
            split_root,
            split_root / 'training_data',
            split_root / 'validation_data',
        ])

    dataset_root = CFG['kaggle_dataset_root']
    candidates.extend([
        dataset_root / 'training_data',
        dataset_root / 'validation_data',
        dataset_root,
    ])

    first_rel = Path(first_image_file)
    first_name = first_rel.name

    dedup = []
    seen = set()
    for root in candidates:
        key = str(root)
        if key in seen:
            continue
        seen.add(key)
        dedup.append(root)

    for root in dedup:
        if (root / first_rel).exists():
            return root
        if (root / first_name).exists():
            return root

    for root in dedup:
        if not root.exists() or not root.is_dir():
            continue
        matches = list(root.rglob(first_name))
        if matches:
            return matches[0].parent

    raise FileNotFoundError(
        f'Image root not found for {annotation_path} with first file {first_image_file}'
    )


def resolve_split_roots(dataset_root: Path) -> Dict[str, Path]:
    split_roots = {
        'training': dataset_root / 'training_data',
        'validation': dataset_root / 'validation_data',
        'test': dataset_root / 'test_data',
    }

    for split_name, split_root in split_roots.items():
        if not split_root.exists():
            raise FileNotFoundError(f'Missing split directory for {split_name}: {split_root}')

    return split_roots


dataset_root = resolve_kaggle_dataset_root()
split_roots = resolve_split_roots(dataset_root)
print(f'Kaggle dataset root: {dataset_root}')
print('Splits:', {k: str(v) for k, v in split_roots.items()})

Kaggle dataset root: /kaggle/input/datasets/lemhui/dentex
Splits: {'training': '/kaggle/input/datasets/lemhui/dentex/training_data', 'validation': '/kaggle/input/datasets/lemhui/dentex/validation_data', 'test': '/kaggle/input/datasets/lemhui/dentex/test_data'}

## 3. Leakage Guardrails And Split Integrity

In [4]:
VALID_IMAGE_SUFFIXES = {'.png', '.jpg', '.jpeg', '.bmp', '.tif', '.tiff'}


def list_split_images(split_name: str, split_root: Path) -> List[Path]:
    if split_name == 'test':
        test_input = split_root / 'disease' / 'input'
        roots = [test_input, split_root]
    else:
        roots = [split_root]

    images: List[Path] = []
    for root in roots:
        if not root.exists():
            continue
        for path in root.rglob('*'):
            if path.is_file() and path.suffix.lower() in VALID_IMAGE_SUFFIXES:
                images.append(path)

    # De-duplicate by resolved path.
    unique = []
    seen = set()
    for path in sorted(images):
        key = str(path.resolve())
        if key not in seen:
            seen.add(key)
            unique.append(path)
    return unique


def load_split_index(split_name: str, split_root: Path) -> pd.DataFrame:
    if split_name in {'training', 'validation'}:
        annotation_path = find_annotation_json(split_root, split_name=split_name)
        print(f"{split_name} annotation: {annotation_path}")
        with annotation_path.open('r', encoding='utf-8') as file:
            payload = json.load(file)

        rows = [
            {
                'split': split_name,
                'image_id': int(image['id']),
                'file_name': str(Path(image['file_name']).name),
                'width': int(image.get('width', -1)),
                'height': int(image.get('height', -1)),
            }
            for image in payload['images']
        ]
        return pd.DataFrame(rows)

    # test split in this Kaggle dataset is not COCO aggregate JSON.
    image_files = list_split_images(split_name, split_root)
    print(f"{split_name} annotation: <labelme-per-image-json>")
    print(f"{split_name} image file count from tree: {len(image_files)}")
    rows = [
        {
            'split': split_name,
            'image_id': idx,
            'file_name': path.name,
            'width': -1,
            'height': -1,
        }
        for idx, path in enumerate(image_files)
    ]
    return pd.DataFrame(rows)


split_indices = []
for name in ['training', 'validation', 'test']:
    split_indices.append(load_split_index(name, split_roots[name]))

split_index = pd.concat(split_indices, ignore_index=True)
display(split_index.groupby('split').size().rename('images').to_frame())
print('Unique filenames by split:')
for name in ['training', 'validation', 'test']:
    n_unique = split_index[split_index['split'] == name]['file_name'].nunique()
    print(f'  {name}: {n_unique}')

training_names = set(split_index[split_index['split'] == 'training']['file_name'])
validation_names = set(split_index[split_index['split'] == 'validation']['file_name'])
test_names = set(split_index[split_index['split'] == 'test']['file_name'])

assert training_names.isdisjoint(validation_names), 'Leakage: training/validation overlap'
assert training_names.isdisjoint(test_names), 'Leakage: training/test overlap'
assert validation_names.isdisjoint(test_names), 'Leakage: validation/test overlap'

print('No filename overlap detected across training, validation, and test splits')

training annotation: /kaggle/input/datasets/lemhui/dentex/training_data/training_data/quadrant-enumeration-disease/train_quadrant_enumeration_disease.json
validation annotation: /kaggle/input/datasets/lemhui/dentex/validation_triple.json
test annotation: <labelme-per-image-json>
test image file count from tree: 250

            images
split
test           250
training       705
validation      50

Unique filenames by split:
  training: 705
  validation: 50
  test: 250
No filename overlap detected across training, validation, and test splits

## 4. Convert Official Splits To YOLO Datasets

Three YOLO datasets are created from the same official boxes: pathology diagnosis, tooth enumeration, and quadrant.

In [5]:
def normalise_label(name: str) -> str:
    return ' '.join(str(name).strip().lower().replace('-', ' ').replace('_', ' ').split())


def label_to_yaml_name(label: str) -> str:
    return normalise_label(label).replace(' ', '_')


def clip_bbox_xywh(
    x: float,
    y: float,
    w: float,
    h: float,
    width: int,
    height: int,
) -> Tuple[float, float, float, float]:
    x1 = max(0.0, x)
    y1 = max(0.0, y)
    x2 = min(float(width), x + max(0.0, w))
    y2 = min(float(height), y + max(0.0, h))
    return x1, y1, max(0.0, x2 - x1), max(0.0, y2 - y1)


def xywh_to_yolo(
    x: float,
    y: float,
    w: float,
    h: float,
    width: int,
    height: int,
) -> Tuple[float, float, float, float]:
    xc = (x + 0.5 * w) / float(width)
    yc = (y + 0.5 * h) / float(height)
    return xc, yc, w / float(width), h / float(height)


def ensure_clean_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def build_pathology_schema(training_split_root: Path) -> Tuple[Dict[int, int], Dict[int, int], List[str], pd.DataFrame]:
    annotation_path = find_annotation_json(training_split_root, split_name='training')
    with annotation_path.open('r', encoding='utf-8') as file:
        payload = json.load(file)

    categories = sorted(payload['categories_3'], key=lambda item: int(item['id']))
    cat3_id_to_cls = {}
    cls_to_cat3_id = {}
    class_names = []
    rows = []

    for cls_idx, category in enumerate(categories):
        cat3_id = int(category['id'])
        cat3_name = normalise_label(category['name'])
        cat3_id_to_cls[cat3_id] = cls_idx
        cls_to_cat3_id[cls_idx] = cat3_id
        class_names.append(label_to_yaml_name(cat3_name))
        rows.append(
            {
                'cat3_id': cat3_id,
                'cat3_name': cat3_name,
                'model_cls': cls_idx,
                'yaml_name': label_to_yaml_name(cat3_name),
            }
        )

    schema_df = pd.DataFrame(rows)
    return cat3_id_to_cls, cls_to_cat3_id, class_names, schema_df


def convert_split_to_yolo(
    source_split: str,
    output_split: str,
    task_name: str,
    output_root: Path,
    pathology_cat3_to_cls: Dict[int, int],
) -> Dict[str, object]:
    if source_split not in {'training', 'validation'}:
        raise ValueError(f'COCO conversion is only supported for training/validation, got: {source_split}')

    split_root = split_roots[source_split]
    annotation_path = find_annotation_json(split_root, split_name=source_split)

    with annotation_path.open('r', encoding='utf-8') as file:
        payload = json.load(file)

    images = payload['images']
    annotations = payload['annotations']

    by_image = defaultdict(list)
    for annotation in annotations:
        by_image[int(annotation['image_id'])].append(annotation)

    image_root = find_image_root(annotation_path, images[0]['file_name'], split_root=split_root)

    image_dir = output_root / 'images' / output_split
    label_dir = output_root / 'labels' / output_split
    image_dir.mkdir(parents=True, exist_ok=True)
    label_dir.mkdir(parents=True, exist_ok=True)

    kept_images = 0
    kept_boxes = 0
    missing_images = 0

    for image in images:
        image_id = int(image['id'])
        width = int(image['width'])
        height = int(image['height'])
        image_path = image_root / image['file_name']
        if not image_path.exists():
            missing_images += 1
            continue

        lines = []
        for annotation in by_image.get(image_id, []):
            x, y, w, h = [float(v) for v in annotation['bbox']]
            x, y, w, h = clip_bbox_xywh(x, y, w, h, width, height)
            if w <= 1.0 or h <= 1.0:
                continue

            if task_name == 'pathology':
                cat3_id = int(annotation['category_id_3'])
                if cat3_id not in pathology_cat3_to_cls:
                    continue
                cls_id = pathology_cat3_to_cls[cat3_id]
            elif task_name == 'tooth_enumeration':
                cls_id = int(annotation['category_id_2'])
                if not (0 <= cls_id < 8):
                    continue
            elif task_name == 'quadrant':
                cls_id = int(annotation['category_id_1'])
                if not (0 <= cls_id < 4):
                    continue
            else:
                raise ValueError(f'Unsupported task: {task_name}')

            xc, yc, wn, hn = xywh_to_yolo(x, y, w, h, width, height)
            lines.append(f'{cls_id} {xc:.6f} {yc:.6f} {wn:.6f} {hn:.6f}')

        dst_image = image_dir / Path(image['file_name']).name
        dst_label = label_dir / f"{Path(image['file_name']).stem}.txt"
        shutil.copy2(image_path, dst_image)
        if lines:
            dst_label.write_text('\n'.join(lines) + '\n', encoding='utf-8')
        else:
            dst_label.write_text('', encoding='utf-8')

        kept_images += 1
        kept_boxes += len(lines)

    split_txt = output_root / f'{output_split}.txt'
    image_paths = sorted(str(path.resolve()) for path in image_dir.glob('*'))
    split_txt.write_text('\n'.join(image_paths) + '\n', encoding='utf-8')

    if missing_images:
        print(f'Skipped missing images in {source_split}: {missing_images}')

    return {
        'task': task_name,
        'source_split': source_split,
        'output_split': output_split,
        'images': kept_images,
        'boxes': kept_boxes,
        'annotation_path': str(annotation_path),
    }


def write_dataset_yaml(dataset_root: Path, class_names: List[str]) -> Path:
    yaml_lines = [
        f'path: {dataset_root.resolve()}',
        'train: train.txt',
        'val: validation.txt',
        'test: test.txt',
        'names:',
    ]
    yaml_lines += [f'  {idx}: {name}' for idx, name in enumerate(class_names)]
    yaml_path = dataset_root / 'dataset.yaml'
    yaml_path.write_text('\n'.join(yaml_lines) + '\n', encoding='utf-8')
    return yaml_path


def write_test_lists_for_tasks(task_roots: List[Path]) -> None:
    test_images = list_split_images('test', split_roots['test'])
    test_paths = [str(path.resolve()) for path in test_images]

    for task_root in task_roots:
        (task_root / 'images' / 'test').mkdir(parents=True, exist_ok=True)
        (task_root / 'labels' / 'test').mkdir(parents=True, exist_ok=True)
        (task_root / 'test.txt').write_text('\n'.join(test_paths) + '\n', encoding='utf-8')

    print(f'Wrote test image lists with {len(test_paths)} images')


PATHOLOGY_CAT3_TO_CLS, PATHOLOGY_CLS_TO_CAT3, pathology_class_names, pathology_schema_df = build_pathology_schema(
    split_roots['training']
)
CFG['pathology_class_names'] = pathology_class_names

print('Pathology class mapping:')
display(pathology_schema_df)

pathology_root = CFG['yolo_root'] / 'pathology'
tooth_root = CFG['yolo_root'] / 'tooth_enumeration'
quadrant_root = CFG['yolo_root'] / 'quadrant'
ensure_clean_dir(pathology_root)
ensure_clean_dir(tooth_root)
ensure_clean_dir(quadrant_root)

conversion_rows = []
split_mapping = {
    'train': 'training',
    'validation': 'validation',
}

for output_split, source_split in split_mapping.items():
    conversion_rows.append(
        convert_split_to_yolo(
            source_split=source_split,
            output_split=output_split,
            task_name='pathology',
            output_root=pathology_root,
            pathology_cat3_to_cls=PATHOLOGY_CAT3_TO_CLS,
        )
    )
    conversion_rows.append(
        convert_split_to_yolo(
            source_split=source_split,
            output_split=output_split,
            task_name='tooth_enumeration',
            output_root=tooth_root,
            pathology_cat3_to_cls=PATHOLOGY_CAT3_TO_CLS,
        )
    )
    conversion_rows.append(
        convert_split_to_yolo(
            source_split=source_split,
            output_split=output_split,
            task_name='quadrant',
            output_root=quadrant_root,
            pathology_cat3_to_cls=PATHOLOGY_CAT3_TO_CLS,
        )
    )

write_test_lists_for_tasks([pathology_root, tooth_root, quadrant_root])

pathology_yaml = write_dataset_yaml(pathology_root, CFG['pathology_class_names'])
tooth_yaml = write_dataset_yaml(tooth_root, CFG['enumeration_class_names'])
quadrant_yaml = write_dataset_yaml(quadrant_root, CFG['quadrant_class_names'])

conversion_df = pd.DataFrame(conversion_rows)
display(conversion_df)
print(f'Pathology data YAML: {pathology_yaml}')
print(f'Tooth enumeration data YAML: {tooth_yaml}')
print(f'Quadrant data YAML: {quadrant_yaml}')

Pathology class mapping:

   cat3_id          cat3_name  model_cls          yaml_name
0        0           impacted          0           impacted
1        1             caries          1             caries
2        2  periapical lesion          2  periapical_lesion
3        3        deep caries          3        deep_caries

Wrote test image lists with 250 images

,task,source_split,output_split,images,boxes,annotation_path
0,pathology,training,train,705,3529,/kaggle/input/datasets/lemhui/dentex/training_...
1,tooth_enumeration,training,train,705,3529,/kaggle/input/datasets/lemhui/dentex/training_...
2,quadrant,training,train,705,3529,/kaggle/input/datasets/lemhui/dentex/training_...
3,pathology,validation,validation,50,182,/kaggle/input/datasets/lemhui/dentex/validatio...
4,tooth_enumeration,validation,validation,50,182,/kaggle/input/datasets/lemhui/dentex/validatio...
5,quadrant,validation,validation,50,182,/kaggle/input/datasets/lemhui/dentex/validatio...

Pathology data YAML: /kaggle/working/dentex_final_model_c/yolo/pathology/dataset.yaml
Tooth enumeration data YAML: /kaggle/working/dentex_final_model_c/yolo/tooth_enumeration/dataset.yaml
Quadrant data YAML: /kaggle/working/dentex_final_model_c/yolo/quadrant/dataset.yaml

## 5. YOLO Training Helper

In [6]:
def patch_ray_session_api() -> None:
    try:
        import ray.train._internal.session as ray_session
    except Exception as err:
        print(f'Ray patch skipped: {err}')
        return

    if not hasattr(ray_session, '_get_session'):
        def _get_session():
            return None

        ray_session._get_session = _get_session
        print('Applied Ray callback compatibility patch.')


def patch_ultralytics_ray_callback() -> None:
    try:
        from ultralytics.utils.callbacks import raytune as raytune_cb
    except Exception:
        return

    def _noop_on_fit_epoch_end(trainer):
        return None

    raytune_cb.on_fit_epoch_end = _noop_on_fit_epoch_end

    try:
        from ultralytics.utils.callbacks import base as callback_base

        for event, callbacks in callback_base.default_callbacks.items():
            callback_base.default_callbacks[event] = [
                cb for cb in callbacks if getattr(cb, '__module__', '') != raytune_cb.__name__
            ]
    except Exception:
        pass


def disable_ray_tune_callbacks(model: YOLO) -> None:
    removed = 0
    for event, callbacks in model.callbacks.items():
        kept = [cb for cb in callbacks if 'raytune' not in cb.__module__]
        removed += len(callbacks) - len(kept)
        model.callbacks[event] = kept
    if removed:
        print(f'Removed {removed} Ray Tune callback(s) from Ultralytics model')


class LineEpochIterator:
    def __init__(self, iterable=None, *args, **kwargs):
        self.iterable = iterable if iterable is not None else []
        self.description = None

    def __iter__(self):
        for item in self.iterable:
            yield item
        if self.description:
            print(str(self.description).strip())

    def set_description(self, description=None, refresh=True):
        self.description = description

    def update(self, n=1):
        return None

    def close(self):
        return None

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.close()


class UltralyticsEpochHeaderFilter:
    def filter(self, record):
        message = record.getMessage().strip()
        return not message.startswith('Epoch')


def patch_ultralytics_epoch_output() -> None:
    from ultralytics import utils as ultralytics_utils
    from ultralytics.engine import trainer as ultralytics_trainer

    setattr(ultralytics_utils, 'T' + 'QDM', LineEpochIterator)
    setattr(ultralytics_trainer, 'T' + 'QDM', LineEpochIterator)

    try:
        from ultralytics.engine import validator as ultralytics_validator

        setattr(ultralytics_validator, 'T' + 'QDM', LineEpochIterator)
    except Exception:
        pass

    logger = ultralytics_utils.LOGGER
    if not any(isinstance(item, UltralyticsEpochHeaderFilter) for item in logger.filters):
        logger.addFilter(UltralyticsEpochHeaderFilter())


def experiment_value(exp_cfg: dict, key: str):
    if CFG['sanity_mode'] and key in {'epochs', 'imgsz'}:
        return CFG[key]
    return exp_cfg.get(key, CFG[key])


def train_yolo_baseline(
    model_source: str,
    run_name: str,
    data_yaml: Path,
    exp_cfg: dict,
) -> Tuple[object, Path]:
    patch_ray_session_api()
    patch_ultralytics_ray_callback()
    patch_ultralytics_epoch_output()

    model = YOLO(model_source)
    disable_ray_tune_callbacks(model)

    start = time.time()
    result = model.train(
        data=str(data_yaml),
        epochs=experiment_value(exp_cfg, 'epochs'),
        imgsz=experiment_value(exp_cfg, 'imgsz'),
        batch=CFG['batch'],
        project=str(CFG['runs_root']),
        name=run_name,
        exist_ok=True,
        device=CFG['device'],
        workers=CFG['workers'],
        cache=CFG['cache'],
        optimizer=CFG['optimizer'],
        lr0=exp_cfg.get('lr0', CFG['lr0']),
        patience=exp_cfg.get('patience', CFG['patience']),
        seed=SEED,
        deterministic=True,
        weight_decay=exp_cfg.get('weight_decay', CFG['weight_decay']),
        mosaic=exp_cfg.get('mosaic', CFG['mosaic']),
        mixup=CFG['mixup'],
        degrees=exp_cfg.get('degrees', CFG['degrees']),
        translate=CFG['translate'],
        scale=exp_cfg.get('scale', CFG['scale']),
        hsv_h=CFG['hsv_h'],
        hsv_s=CFG['hsv_s'],
        hsv_v=CFG['hsv_v'],
        fliplr=CFG['fliplr'],
        flipud=CFG['flipud'],
        plots=False,
        verbose=False,
        fraction=CFG['sanity_fraction'] if CFG['sanity_mode'] else 1.0,
    )
    elapsed = round(time.time() - start, 2)

    run_dir = CFG['runs_root'] / run_name
    best_weights = run_dir / 'weights' / 'best.pt'
    print(f'Run: {run_name}')
    print(f'Elapsed seconds: {elapsed}')
    print(f'Best weights: {best_weights}')
    return result, best_weights

def write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, separators=(',', ':')), encoding='utf-8')


def path_size_bytes(path: Path) -> int:
    if not path.exists():
        return 0
    if path.is_file() or path.is_symlink():
        return path.stat().st_size
    return sum(item.stat().st_size for item in path.rglob('*') if item.is_file())


def remove_path(path: Path) -> int:
    size_bytes = path_size_bytes(path)
    if path.is_dir():
        shutil.rmtree(path)
    elif path.exists():
        path.unlink()
    return size_bytes


def prune_heavy_outputs(keep_weight_paths: List[Path]) -> None:
    if not CFG['prune_heavy_outputs']:
        print('Heavy output pruning disabled.')
        return

    keep_paths = {path.resolve() for path in keep_weight_paths if path.exists()}
    removed_bytes = 0
    removed_items = []

    for transient_dir in [CFG['yolo_root'], CFG['official_eval_root']]:
        if transient_dir.exists():
            removed_bytes += remove_path(transient_dir)
            removed_items.append(str(transient_dir))

    if CFG['runs_root'].exists():
        for path in CFG['runs_root'].rglob('*'):
            if not path.is_file():
                continue
            if path.resolve() in keep_paths:
                continue
            if path.name == 'results.csv':
                continue
            removed_bytes += remove_path(path)

        for run_dir in sorted(CFG['runs_root'].glob('*')):
            if run_dir.is_dir() and not any(run_dir.rglob('*')):
                run_dir.rmdir()

    for model_name in ['yolo11n.pt', 'yolo11s.pt']:
        model_path = Path(model_name)
        if model_path.exists():
            removed_bytes += remove_path(model_path)
            removed_items.append(str(model_path))

    print(f'Pruned {removed_bytes / (1024 * 1024):.2f} MB of transient output files.')
    if removed_items:
        print('Removed transient directories/files:')
        for item in removed_items:
            print(f'- {item}')

## 6. Shared Prediction And Evaluation Helpers

These helpers mirror the original notebook so Model C can be compared with the same COCO-style metrics.

In [7]:
@dataclass
class DetectedBox:
    cls_id: int
    score: float
    x1: float
    y1: float
    x2: float
    y2: float

    @property
    def cx(self) -> float:
        return 0.5 * (self.x1 + self.x2)

    @property
    def cy(self) -> float:
        return 0.5 * (self.y1 + self.y2)


def yolo_to_boxes(prediction_result) -> List[DetectedBox]:
    if prediction_result.boxes is None:
        return []

    xyxy = prediction_result.boxes.xyxy.cpu().numpy()
    cls_ids = prediction_result.boxes.cls.cpu().numpy().astype(int)
    scores = prediction_result.boxes.conf.cpu().numpy()

    boxes = []
    for coords, cls_id, score in zip(xyxy, cls_ids, scores):
        boxes.append(
            DetectedBox(
                cls_id=int(cls_id),
                score=float(score),
                x1=float(coords[0]),
                y1=float(coords[1]),
                x2=float(coords[2]),
                y2=float(coords[3]),
            )
        )
    return boxes


def iou_xyxy(a: DetectedBox, b: DetectedBox) -> float:
    inter_x1 = max(a.x1, b.x1)
    inter_y1 = max(a.y1, b.y1)
    inter_x2 = min(a.x2, b.x2)
    inter_y2 = min(a.y2, b.y2)

    inter_w = max(0.0, inter_x2 - inter_x1)
    inter_h = max(0.0, inter_y2 - inter_y1)
    inter = inter_w * inter_h

    area_a = max(0.0, a.x2 - a.x1) * max(0.0, a.y2 - a.y1)
    area_b = max(0.0, b.x2 - b.x1) * max(0.0, b.y2 - b.y1)
    union = area_a + area_b - inter
    if union <= 0:
        return 0.0
    return inter / union


def bbox_iou_xywh(a, b) -> float:
    ax1, ay1, aw, ah = a
    bx1, by1, bw, bh = b
    ax2, ay2 = ax1 + aw, ay1 + ah
    bx2, by2 = bx1 + bw, by1 + bh

    ix1, iy1 = max(ax1, bx1), max(ay1, by1)
    ix2, iy2 = min(ax2, bx2), min(ay2, by2)

    iw, ih = max(0.0, ix2 - ix1), max(0.0, iy2 - iy1)
    inter = iw * ih
    union = aw * ah + bw * bh - inter
    return inter / union if union > 0 else 0.0


def xyxy_to_xywh(box: DetectedBox) -> List[float]:
    return [box.x1, box.y1, max(0.0, box.x2 - box.x1), max(0.0, box.y2 - box.y1)]


def load_gt_payload(split_name: str) -> dict:
    annotation_path = find_annotation_json(split_roots[split_name], split_name=split_name)
    with annotation_path.open('r', encoding='utf-8') as file:
        return json.load(file)


def diagnosis_name_to_gt_id(gt_payload: dict) -> Dict[str, int]:
    mapping = {}
    for category in gt_payload['categories_3']:
        mapping[normalise_label(category['name'])] = int(category['id'])
    return mapping


def diagnosis_pred_to_gt_id_map(gt_payload: dict) -> Dict[int, int]:
    gt_name_to_id = diagnosis_name_to_gt_id(gt_payload)
    pred_map = {}
    for cls_idx, cat3_id in PATHOLOGY_CLS_TO_CAT3.items():
        row = pathology_schema_df[pathology_schema_df['model_cls'] == cls_idx].iloc[0]
        train_name = normalise_label(row['cat3_name'])
        if train_name in gt_name_to_id:
            pred_map[cls_idx] = int(gt_name_to_id[train_name])
        else:
            pred_map[cls_idx] = int(cat3_id)
    return pred_map


def learn_quadrant_orientation(training_split_root: Path) -> Dict[str, int]:
    annotation_path = find_annotation_json(training_split_root, split_name='training')
    with annotation_path.open('r', encoding='utf-8') as file:
        payload = json.load(file)

    image_by_id = {int(img['id']): img for img in payload['images']}

    rows = []
    for annotation in payload['annotations']:
        img = image_by_id[int(annotation['image_id'])]
        x, y, w, h = annotation['bbox']
        cx_norm = (float(x) + 0.5 * float(w)) / float(img['width'])
        rows.append({'quadrant': int(annotation['category_id_1']), 'cx_norm': cx_norm})

    df = pd.DataFrame(rows)
    upper_ids = [0, 1]
    lower_ids = [2, 3]

    upper_mean = df[df['quadrant'].isin(upper_ids)].groupby('quadrant')['cx_norm'].mean()
    lower_mean = df[df['quadrant'].isin(lower_ids)].groupby('quadrant')['cx_norm'].mean()

    return {
        'upper_left': int(upper_mean.idxmin()),
        'upper_right': int(upper_mean.idxmax()),
        'lower_left': int(lower_mean.idxmin()),
        'lower_right': int(lower_mean.idxmax()),
    }


def get_pca_axes(centres: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    if centres.shape[0] < 2:
        return np.array([-1.0, 0.0], dtype=float), np.array([0.0, 1.0], dtype=float)

    centred = centres - centres.mean(axis=0, keepdims=True)
    _, _, vh = np.linalg.svd(centred, full_matrices=False)

    major_axis = vh[0]
    if vh.shape[0] >= 2:
        minor_axis = vh[1]
    else:
        minor_axis = np.array([0.0, 1.0], dtype=float)

    if major_axis[0] > 0:
        major_axis = -major_axis
    return major_axis, minor_axis


def assign_quadrant_from_layout(
    tooth_boxes: List[DetectedBox],
    orientation_map: Dict[str, int],
) -> Dict[int, int]:
    if not tooth_boxes:
        return {}

    if len(tooth_boxes) == 1:
        return {0: orientation_map['upper_left']}

    centres = np.array([[box.cx, box.cy] for box in tooth_boxes], dtype=float)
    major_axis, minor_axis = get_pca_axes(centres)

    major_scores = centres @ major_axis
    minor_scores = centres @ minor_axis
    major_split = float(np.median(major_scores))
    minor_split = float(np.median(minor_scores))

    mapping = {}
    for idx in range(len(tooth_boxes)):
        is_left = major_scores[idx] <= major_split
        is_upper = minor_scores[idx] <= minor_split
        if is_upper and is_left:
            mapping[idx] = orientation_map['upper_left']
        elif is_upper and not is_left:
            mapping[idx] = orientation_map['upper_right']
        elif not is_upper and is_left:
            mapping[idx] = orientation_map['lower_left']
        else:
            mapping[idx] = orientation_map['lower_right']

    return mapping


def assign_pathology_to_teeth(
    pathology_boxes: List[DetectedBox],
    tooth_boxes: List[DetectedBox],
) -> Dict[int, int]:
    if not pathology_boxes or not tooth_boxes:
        return {}

    cost = np.zeros((len(pathology_boxes), len(tooth_boxes)), dtype=float)

    for i, path_box in enumerate(pathology_boxes):
        for j, tooth_box in enumerate(tooth_boxes):
            overlap = iou_xyxy(path_box, tooth_box)
            dist = math.dist((path_box.cx, path_box.cy), (tooth_box.cx, tooth_box.cy))
            area_path = max(1.0, (path_box.x2 - path_box.x1) * (path_box.y2 - path_box.y1))
            area_tooth = max(1.0, (tooth_box.x2 - tooth_box.x1) * (tooth_box.y2 - tooth_box.y1))
            size_penalty = abs(math.log(area_path / area_tooth))
            cost[i, j] = (
                0.60 * (1.0 - overlap)
                + 0.30 * min(1.0, dist / 400.0)
                + 0.10 * min(1.0, size_penalty / 3.0)
            )

    row_ind, col_ind = linear_sum_assignment(cost)

    assignment = {}
    for row, col in zip(row_ind, col_ind):
        overlap = iou_xyxy(pathology_boxes[row], tooth_boxes[col])
        dist = math.dist(
            (pathology_boxes[row].cx, pathology_boxes[row].cy),
            (tooth_boxes[col].cx, tooth_boxes[col].cy),
        )
        if overlap < 0.01 and dist > 320:
            continue
        assignment[row] = col

    return assignment


def assign_pathology_to_teeth_nearest(
    pathology_boxes: List[DetectedBox],
    tooth_boxes: List[DetectedBox],
) -> Dict[int, int]:
    if not pathology_boxes or not tooth_boxes:
        return {}

    assignment = {}
    for i, path_box in enumerate(pathology_boxes):
        distances = [
            math.dist((path_box.cx, path_box.cy), (tooth_box.cx, tooth_box.cy))
            for tooth_box in tooth_boxes
        ]
        j = int(np.argmin(distances))
        if distances[j] <= 400:
            assignment[i] = j

    return assignment


def assign_pathology_to_teeth_iou_first(
    pathology_boxes: List[DetectedBox],
    tooth_boxes: List[DetectedBox],
) -> Dict[int, int]:
    if not pathology_boxes or not tooth_boxes:
        return {}

    assignment = {}
    used_teeth = set()

    for i, path_box in enumerate(pathology_boxes):
        scores = []
        for j, tooth_box in enumerate(tooth_boxes):
            if j in used_teeth:
                scores.append(-1.0)
            else:
                overlap = iou_xyxy(path_box, tooth_box)
                dist = math.dist((path_box.cx, path_box.cy), (tooth_box.cx, tooth_box.cy))
                scores.append(overlap - 0.001 * dist)

        j = int(np.argmax(scores))
        if scores[j] > -0.3:
            assignment[i] = j
            used_teeth.add(j)

    return assignment


def assign_pathology_to_teeth_by_mode(
    pathology_boxes: List[DetectedBox],
    tooth_boxes: List[DetectedBox],
    assignment_mode: str,
) -> Dict[int, int]:
    if assignment_mode == 'hungarian':
        return assign_pathology_to_teeth(pathology_boxes, tooth_boxes)
    if assignment_mode == 'nearest':
        return assign_pathology_to_teeth_nearest(pathology_boxes, tooth_boxes)
    if assignment_mode == 'iou_first':
        return assign_pathology_to_teeth_iou_first(pathology_boxes, tooth_boxes)
    raise ValueError(f'Unknown assignment_mode: {assignment_mode}')


def fuse_boxes_weighted(
    boxes: List[DetectedBox],
    iou_thr: float,
) -> List[DetectedBox]:
    if not boxes:
        return []

    boxes_sorted = sorted(boxes, key=lambda item: item.score, reverse=True)
    fused = []

    while boxes_sorted:
        anchor = boxes_sorted.pop(0)
        cluster = [anchor]
        remaining = []

        for candidate in boxes_sorted:
            if candidate.cls_id == anchor.cls_id and iou_xyxy(anchor, candidate) >= iou_thr:
                cluster.append(candidate)
            else:
                remaining.append(candidate)
        boxes_sorted = remaining

        weights = np.array([item.score for item in cluster], dtype=float)
        weights = np.maximum(weights, 1e-6)

        x1 = float(np.average([item.x1 for item in cluster], weights=weights))
        y1 = float(np.average([item.y1 for item in cluster], weights=weights))
        x2 = float(np.average([item.x2 for item in cluster], weights=weights))
        y2 = float(np.average([item.y2 for item in cluster], weights=weights))
        score = float(np.max([item.score for item in cluster]))

        fused.append(
            DetectedBox(
                cls_id=anchor.cls_id,
                score=score,
                x1=x1,
                y1=y1,
                x2=x2,
                y2=y2,
            )
        )

    return fused


def predict_boxes_with_tta(
    model: YOLO,
    image_path: str,
    conf: float,
    iou: float,
    enable_tta: bool,
) -> List[DetectedBox]:
    base_result = model.predict(source=image_path, conf=conf, iou=iou, verbose=False)[0]
    base_boxes = yolo_to_boxes(base_result)
    if not enable_tta:
        return base_boxes

    image_np = np.array(Image.open(image_path).convert('RGB'))
    width = int(image_np.shape[1])
    image_flip = np.ascontiguousarray(image_np[:, ::-1, :])

    flip_result = model.predict(source=image_flip, conf=conf, iou=iou, verbose=False)[0]
    flip_boxes = yolo_to_boxes(flip_result)

    flip_boxes_unflipped = []
    for box in flip_boxes:
        flip_boxes_unflipped.append(
            DetectedBox(
                cls_id=box.cls_id,
                score=box.score,
                x1=float(width - box.x2),
                y1=box.y1,
                x2=float(width - box.x1),
                y2=box.y2,
            )
        )

    merged = base_boxes + flip_boxes_unflipped
    return fuse_boxes_weighted(merged, iou_thr=CFG['tta_fusion_iou'])


def parse_test_image_id(file_name: str) -> int:
    stem = Path(file_name).stem
    if stem.startswith('test_'):
        return int(stem.split('_')[-1])
    raise ValueError(f'Cannot parse test image id from filename: {file_name}')


def build_predictions_for_split(
    split_name: str,
    image_paths: List[str],
    image_id_lookup: Dict[str, int],
    pathology_model: YOLO,
    tooth_model: YOLO,
    diagnosis_id_map: Dict[int, int],
    orientation_map: Dict[str, int],
    pathology_conf: float,
    tooth_conf: float,
    predict_iou: float,
    enable_tta: bool,
    assignment_mode: str = 'hungarian',
) -> Tuple[List[dict], List[dict]]:
    unified_predictions = []
    challenge_boxes = []

    for image_path in image_paths:
        file_name = Path(image_path).name
        if file_name not in image_id_lookup:
            continue

        image_id = int(image_id_lookup[file_name])

        pathology_boxes = predict_boxes_with_tta(
            model=pathology_model,
            image_path=image_path,
            conf=pathology_conf,
            iou=predict_iou,
            enable_tta=enable_tta,
        )
        tooth_boxes = predict_boxes_with_tta(
            model=tooth_model,
            image_path=image_path,
            conf=tooth_conf,
            iou=predict_iou,
            enable_tta=enable_tta,
        )

        if not pathology_boxes or not tooth_boxes:
            continue

        quadrant_by_tooth_idx = assign_quadrant_from_layout(tooth_boxes, orientation_map)
        assign_map = assign_pathology_to_teeth_by_mode(
            pathology_boxes=pathology_boxes,
            tooth_boxes=tooth_boxes,
            assignment_mode=assignment_mode,
        )

        for path_idx, tooth_idx in assign_map.items():
            if tooth_idx not in quadrant_by_tooth_idx:
                continue

            path_box = pathology_boxes[path_idx]
            tooth_box = tooth_boxes[tooth_idx]
            if path_box.cls_id not in diagnosis_id_map:
                continue

            quadrant_id = int(quadrant_by_tooth_idx[tooth_idx])
            enumeration_id = int(tooth_box.cls_id)
            diagnosis_id = int(diagnosis_id_map[path_box.cls_id])

            unified_predictions.append(
                {
                    'image_id': image_id,
                    'bbox': xyxy_to_xywh(path_box),
                    'score': float(path_box.score),
                    'quadrant': quadrant_id,
                    'enumeration': enumeration_id,
                    'diagnosis': diagnosis_id,
                }
            )

            challenge_boxes.append(
                {
                    'name': f'{quadrant_id} - {enumeration_id} - {diagnosis_id}',
                    'corners': [
                        [float(path_box.x1), float(path_box.y1), image_id],
                        [float(path_box.x1), float(path_box.y2), image_id],
                        [float(path_box.x2), float(path_box.y1), image_id],
                        [float(path_box.x2), float(path_box.y2), image_id],
                    ],
                    'probability': float(path_box.score),
                }
            )

    print(f'{split_name} prediction count: {len(unified_predictions)}')
    return unified_predictions, challenge_boxes


def build_predictions_with_gt_teeth_for_split(
    split_name: str,
    image_paths: List[str],
    image_id_lookup: Dict[str, int],
    gt_payload: dict,
    pathology_model: YOLO,
    diagnosis_id_map: Dict[int, int],
    pathology_conf: float,
    predict_iou: float,
    enable_tta: bool,
    assignment_mode: str = 'hungarian',
) -> List[dict]:
    gt_teeth_by_image = defaultdict(list)
    for ann in gt_payload['annotations']:
        x, y, w, h = ann['bbox']
        gt_teeth_by_image[int(ann['image_id'])].append(
            {
                'box': DetectedBox(
                    cls_id=int(ann['category_id_2']),
                    score=1.0,
                    x1=float(x),
                    y1=float(y),
                    x2=float(x + w),
                    y2=float(y + h),
                ),
                'quadrant': int(ann['category_id_1']),
                'enumeration': int(ann['category_id_2']),
            }
        )

    unified_predictions = []

    for image_path in image_paths:
        file_name = Path(image_path).name
        if file_name not in image_id_lookup:
            continue

        image_id = int(image_id_lookup[file_name])
        gt_teeth = gt_teeth_by_image.get(image_id, [])
        if not gt_teeth:
            continue

        pathology_boxes = predict_boxes_with_tta(
            model=pathology_model,
            image_path=image_path,
            conf=pathology_conf,
            iou=predict_iou,
            enable_tta=enable_tta,
        )
        if not pathology_boxes:
            continue

        gt_tooth_boxes = [item['box'] for item in gt_teeth]
        assign_map = assign_pathology_to_teeth_by_mode(
            pathology_boxes=pathology_boxes,
            tooth_boxes=gt_tooth_boxes,
            assignment_mode=assignment_mode,
        )

        for path_idx, tooth_idx in assign_map.items():
            path_box = pathology_boxes[path_idx]
            if path_box.cls_id not in diagnosis_id_map:
                continue

            gt_tooth = gt_teeth[tooth_idx]
            unified_predictions.append(
                {
                    'image_id': image_id,
                    'bbox': xyxy_to_xywh(path_box),
                    'score': float(path_box.score),
                    'quadrant': int(gt_tooth['quadrant']),
                    'enumeration': int(gt_tooth['enumeration']),
                    'diagnosis': int(diagnosis_id_map[path_box.cls_id]),
                }
            )

    print(f'{split_name} GT-tooth-oracle prediction count: {len(unified_predictions)}')
    return unified_predictions


def evaluate_task_quiet(
    gt_payload: dict,
    predictions: List[dict],
    task_name: str,
    category_field: str,
    categories_key: str,
    prefix: str,
) -> Dict[str, float]:
    gt_eval_payload = {
        'images': gt_payload['images'],
        'annotations': [],
        'categories': gt_payload[categories_key],
    }

    for annotation in gt_payload['annotations']:
        gt_eval_payload['annotations'].append(
            {
                'id': int(annotation['id']),
                'image_id': int(annotation['image_id']),
                'bbox': annotation['bbox'],
                'area': float(annotation.get('area', annotation['bbox'][2] * annotation['bbox'][3])),
                'iscrowd': int(annotation.get('iscrowd', 0)),
                'category_id': int(annotation[category_field]),
            }
        )

    pred_eval = [
        {
            'image_id': int(pred['image_id']),
            'bbox': pred['bbox'],
            'score': float(pred['score']),
            'category_id': int(pred[task_name]),
        }
        for pred in predictions
    ]

    if not pred_eval:
        return {'AP': 0.0, 'AP50': 0.0, 'AP75': 0.0, 'AR': 0.0}

    gt_file = CFG['official_eval_root'] / f'{prefix}_gt_{task_name}.json'
    pred_file = CFG['official_eval_root'] / f'{prefix}_pred_{task_name}.json'
    write_json(gt_file, gt_eval_payload)
    write_json(pred_file, pred_eval)

    coco_gt = COCO(str(gt_file))
    coco_pred = coco_gt.loadRes(str(pred_file))

    evaluator = COCOeval(coco_gt, coco_pred, 'bbox')
    with contextlib.redirect_stdout(io.StringIO()):
        evaluator.evaluate()
        evaluator.accumulate()
        evaluator.summarize()

    return {
        'AP': float(evaluator.stats[0]),
        'AP50': float(evaluator.stats[1]),
        'AP75': float(evaluator.stats[2]),
        'AR': float(evaluator.stats[8]),
    }


def evaluate_all_tasks(gt_payload: dict, predictions: List[dict], prefix: str) -> Dict[str, Dict[str, float]]:
    return {
        'Quadrant': evaluate_task_quiet(
            gt_payload=gt_payload,
            predictions=predictions,
            task_name='quadrant',
            category_field='category_id_1',
            categories_key='categories_1',
            prefix=f'{prefix}_quadrant',
        ),
        'Enumeration': evaluate_task_quiet(
            gt_payload=gt_payload,
            predictions=predictions,
            task_name='enumeration',
            category_field='category_id_2',
            categories_key='categories_2',
            prefix=f'{prefix}_enumeration',
        ),
        'Diagnosis': evaluate_task_quiet(
            gt_payload=gt_payload,
            predictions=predictions,
            task_name='diagnosis',
            category_field='category_id_3',
            categories_key='categories_3',
            prefix=f'{prefix}_diagnosis',
        ),
    }


def aggregate_task_metrics(metrics_by_task: Dict[str, Dict[str, float]]) -> Dict[str, float]:
    return {
        metric: float(np.mean([metrics_by_task[task][metric] for task in metrics_by_task]))
        for metric in ['AP', 'AP50', 'AP75', 'AR']
    }


def compute_validation_aggregate_metrics(gt_payload: dict, predictions: List[dict], prefix: str) -> Dict[str, float]:
    return aggregate_task_metrics(evaluate_all_tasks(gt_payload, predictions, prefix))


def experiment_result_row(
    exp: dict,
    metrics_by_task: Dict[str, Dict[str, float]],
    n_predictions: int,
) -> dict:
    aggregate = aggregate_task_metrics(metrics_by_task)
    return {
        'experiment': exp['name'],
        'pathology_model': exp['pathology_model'],
        'tooth_model': exp['tooth_model'],
        'imgsz': experiment_value(exp, 'imgsz'),
        'mosaic': exp['mosaic'],
        'scale': exp['scale'],
        'degrees': exp['degrees'],
        'tta': exp['enable_tta'],
        'assignment_mode': exp['assignment_mode'],
        'n_predictions': n_predictions,
        'quadrant_AP50': metrics_by_task['Quadrant']['AP50'],
        'enumeration_AP50': metrics_by_task['Enumeration']['AP50'],
        'diagnosis_AP50': metrics_by_task['Diagnosis']['AP50'],
        'aggregate_AP50': aggregate['AP50'],
        'quadrant_AP': metrics_by_task['Quadrant']['AP'],
        'enumeration_AP': metrics_by_task['Enumeration']['AP'],
        'diagnosis_AP': metrics_by_task['Diagnosis']['AP'],
        'aggregate_AP': aggregate['AP'],
        'aggregate_AP75': aggregate['AP75'],
        'aggregate_AR': aggregate['AR'],
    }


def evaluate_per_class_ap50(
    gt_payload: dict,
    predictions: List[dict],
    task_name: str,
    category_field: str,
    categories_key: str,
    prefix: str,
) -> pd.DataFrame:
    gt_eval_payload = {
        'images': gt_payload['images'],
        'annotations': [],
        'categories': gt_payload[categories_key],
    }

    for annotation in gt_payload['annotations']:
        gt_eval_payload['annotations'].append(
            {
                'id': int(annotation['id']),
                'image_id': int(annotation['image_id']),
                'bbox': annotation['bbox'],
                'area': float(annotation.get('area', annotation['bbox'][2] * annotation['bbox'][3])),
                'iscrowd': int(annotation.get('iscrowd', 0)),
                'category_id': int(annotation[category_field]),
            }
        )

    pred_eval = [
        {
            'image_id': int(pred['image_id']),
            'bbox': pred['bbox'],
            'score': float(pred['score']),
            'category_id': int(pred[task_name]),
        }
        for pred in predictions
    ]

    if not pred_eval:
        return pd.DataFrame(
            [
                {
                    'task': task_name,
                    'category_id': int(category['id']),
                    'category_name': category.get('name', str(category['id'])),
                    'AP50': np.nan,
                }
                for category in gt_payload[categories_key]
            ]
        )

    gt_file = CFG['official_eval_root'] / f'{prefix}_gt_{task_name}_per_class.json'
    pred_file = CFG['official_eval_root'] / f'{prefix}_pred_{task_name}_per_class.json'
    write_json(gt_file, gt_eval_payload)
    write_json(pred_file, pred_eval)

    coco_gt = COCO(str(gt_file))
    coco_pred = coco_gt.loadRes(str(pred_file))

    evaluator = COCOeval(coco_gt, coco_pred, 'bbox')
    evaluator.params.iouThrs = np.array([0.50])

    with contextlib.redirect_stdout(io.StringIO()):
        evaluator.evaluate()
        evaluator.accumulate()

    precision = evaluator.eval['precision']
    cat_ids = evaluator.params.catIds

    rows = []
    for k, cat_id in enumerate(cat_ids):
        p = precision[0, :, k, 0, -1]
        p = p[p > -1]
        ap50 = float(np.mean(p)) if len(p) else np.nan
        cat = next(c for c in gt_payload[categories_key] if int(c['id']) == int(cat_id))
        rows.append(
            {
                'task': task_name,
                'category_id': int(cat_id),
                'category_name': cat.get('name', str(cat_id)),
                'AP50': ap50,
            }
        )

    return pd.DataFrame(rows)


def error_decomposition(gt_payload: dict, predictions: List[dict], iou_thr: float = 0.5) -> pd.DataFrame:
    gt_by_image = defaultdict(list)
    pred_by_image = defaultdict(list)

    for ann in gt_payload['annotations']:
        gt_by_image[int(ann['image_id'])].append(ann)

    for pred in predictions:
        pred_by_image[int(pred['image_id'])].append(pred)

    rows = []

    for image_id, gt_list in gt_by_image.items():
        pred_list = pred_by_image.get(image_id, [])
        matched_pred = set()

        for gt in gt_list:
            best_iou = 0.0
            best_j = None

            for j, pred in enumerate(pred_list):
                if j in matched_pred:
                    continue
                iou = bbox_iou_xywh(gt['bbox'], pred['bbox'])
                if iou > best_iou:
                    best_iou = iou
                    best_j = j

            if best_j is None or best_iou < iou_thr:
                rows.append(
                    {
                        'image_id': image_id,
                        'error_type': 'false_negative_or_localisation_failure',
                        'iou': best_iou,
                        'gt_quadrant': int(gt['category_id_1']),
                        'gt_enumeration': int(gt['category_id_2']),
                        'gt_diagnosis': int(gt['category_id_3']),
                        'pred_quadrant': None,
                        'pred_enumeration': None,
                        'pred_diagnosis': None,
                    }
                )
                continue

            pred = pred_list[best_j]
            matched_pred.add(best_j)

            quadrant_ok = int(pred['quadrant']) == int(gt['category_id_1'])
            enumeration_ok = int(pred['enumeration']) == int(gt['category_id_2'])
            diagnosis_ok = int(pred['diagnosis']) == int(gt['category_id_3'])

            if quadrant_ok and enumeration_ok and diagnosis_ok:
                error_type = 'correct'
            elif not diagnosis_ok and enumeration_ok:
                error_type = 'diagnosis_error'
            elif diagnosis_ok and not enumeration_ok:
                error_type = 'enumeration_error'
            elif not quadrant_ok:
                error_type = 'quadrant_error'
            else:
                error_type = 'multiple_label_error'

            rows.append(
                {
                    'image_id': image_id,
                    'error_type': error_type,
                    'iou': best_iou,
                    'gt_quadrant': int(gt['category_id_1']),
                    'gt_enumeration': int(gt['category_id_2']),
                    'gt_diagnosis': int(gt['category_id_3']),
                    'pred_quadrant': int(pred['quadrant']),
                    'pred_enumeration': int(pred['enumeration']),
                    'pred_diagnosis': int(pred['diagnosis']),
                }
            )

        for j, pred in enumerate(pred_list):
            if j not in matched_pred:
                rows.append(
                    {
                        'image_id': image_id,
                        'error_type': 'false_positive',
                        'iou': None,
                        'gt_quadrant': None,
                        'gt_enumeration': None,
                        'gt_diagnosis': None,
                        'pred_quadrant': int(pred['quadrant']),
                        'pred_enumeration': int(pred['enumeration']),
                        'pred_diagnosis': int(pred['diagnosis']),
                    }
                )

    return pd.DataFrame(rows)


def apply_oracle_tooth_labels(gt_payload: dict, predictions: List[dict], iou_thr: float = 0.1) -> List[dict]:
    gt_by_image = defaultdict(list)
    for ann in gt_payload['annotations']:
        gt_by_image[int(ann['image_id'])].append(ann)

    oracle_preds = []

    for pred in predictions:
        image_id = int(pred['image_id'])
        gt_list = gt_by_image.get(image_id, [])

        best_iou = 0.0
        best_gt = None
        for gt in gt_list:
            iou = bbox_iou_xywh(gt['bbox'], pred['bbox'])
            if iou > best_iou:
                best_iou = iou
                best_gt = gt

        copied = dict(pred)
        if best_gt is not None and best_iou >= iou_thr:
            copied['quadrant'] = int(best_gt['category_id_1'])
            copied['enumeration'] = int(best_gt['category_id_2'])
        oracle_preds.append(copied)

    return oracle_preds


def bootstrap_metric_ci(
    gt_payload: dict,
    predictions: List[dict],
    n_boot: int = 200,
    seed: int = 42,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    rng = np.random.default_rng(seed)
    image_ids = [int(img['id']) for img in gt_payload['images']]
    image_by_id = {int(img['id']): img for img in gt_payload['images']}

    pred_by_image = defaultdict(list)
    ann_by_image = defaultdict(list)

    for pred in predictions:
        pred_by_image[int(pred['image_id'])].append(pred)

    for ann in gt_payload['annotations']:
        ann_by_image[int(ann['image_id'])].append(ann)

    rows = []

    for b in range(n_boot):
        sampled_ids = rng.choice(image_ids, size=len(image_ids), replace=True)

        sampled_images = []
        sampled_annotations = []
        sampled_predictions = []

        new_img_id = 1
        new_ann_id = 1

        for old_img_id in sampled_ids:
            old_img = image_by_id[int(old_img_id)]
            img_copy = dict(old_img)
            img_copy['id'] = new_img_id
            sampled_images.append(img_copy)

            for ann in ann_by_image.get(int(old_img_id), []):
                ann_copy = dict(ann)
                ann_copy['id'] = new_ann_id
                ann_copy['image_id'] = new_img_id
                sampled_annotations.append(ann_copy)
                new_ann_id += 1

            for pred in pred_by_image.get(int(old_img_id), []):
                pred_copy = dict(pred)
                pred_copy['image_id'] = new_img_id
                sampled_predictions.append(pred_copy)

            new_img_id += 1

        sampled_gt = dict(gt_payload)
        sampled_gt['images'] = sampled_images
        sampled_gt['annotations'] = sampled_annotations

        metrics = compute_validation_aggregate_metrics(
            gt_payload=sampled_gt,
            predictions=sampled_predictions,
            prefix=f'bootstrap_{b}',
        )
        rows.append(metrics)

    boot_df = pd.DataFrame(rows)

    summary = []
    for metric in ['AP', 'AP50', 'AP75', 'AR']:
        summary.append(
            {
                'metric': metric,
                'mean': boot_df[metric].mean(),
                'ci_low': boot_df[metric].quantile(0.025),
                'ci_high': boot_df[metric].quantile(0.975),
            }
        )

    return pd.DataFrame(summary), boot_df


def write_prediction_files(
    split_name: str,
    unified_predictions: List[dict],
    challenge_boxes: List[dict],
) -> Tuple[Path, Path]:
    pred_unified_path = CFG['pred_root'] / f'predictions_unified_{split_name}.json'
    write_json(pred_unified_path, unified_predictions)

    challenge_payload = {
        'name': 'Regions of interest',
        'type': 'Multiple 2D bounding boxes',
        'boxes': challenge_boxes,
        'version': {'major': 1, 'minor': 0},
    }
    pred_challenge_path = CFG['pred_root'] / f'predictions_challenge_format_{split_name}.json'
    write_json(pred_challenge_path, challenge_payload)

    return pred_unified_path, pred_challenge_path

## 7. Final Training, Validation, And Released Test Evaluation

The final configuration trains one pathology model, one tooth enumeration model, and one dedicated quadrant model. Validation metrics are computed from `validation_triple.json`; released-test metrics are computed from the per-image LabelMe JSON files under the test split. Released-test diagnosis labels outside the trained diagnosis label space are skipped before metric calculation.

In [8]:
def build_predictions_with_model_c(
    split_name: str,
    image_paths: List[str],
    image_id_lookup: Dict[str, int],
    pathology_model: YOLO,
    tooth_model: YOLO,
    quadrant_model: YOLO,
    diagnosis_id_map: Dict[int, int],
    pathology_conf: float,
    tooth_conf: float,
    quadrant_conf: float,
    predict_iou: float,
    enable_ab_tta: bool,
    enable_quadrant_tta: bool,
    tooth_assignment_mode: str,
    quadrant_assignment_mode: str,
) -> Tuple[List[dict], List[dict]]:
    unified_predictions = []
    challenge_boxes = []

    for image_path in image_paths:
        file_name = Path(image_path).name
        if file_name not in image_id_lookup:
            continue

        image_id = int(image_id_lookup[file_name])
        pathology_boxes = predict_boxes_with_tta(
            model=pathology_model,
            image_path=image_path,
            conf=pathology_conf,
            iou=predict_iou,
            enable_tta=enable_ab_tta,
        )
        tooth_boxes = predict_boxes_with_tta(
            model=tooth_model,
            image_path=image_path,
            conf=tooth_conf,
            iou=predict_iou,
            enable_tta=enable_ab_tta,
        )
        quadrant_boxes = predict_boxes_with_tta(
            model=quadrant_model,
            image_path=image_path,
            conf=quadrant_conf,
            iou=predict_iou,
            enable_tta=enable_quadrant_tta,
        )

        if not pathology_boxes or not tooth_boxes or not quadrant_boxes:
            continue

        tooth_assignment = assign_pathology_to_teeth_by_mode(
            pathology_boxes=pathology_boxes,
            tooth_boxes=tooth_boxes,
            assignment_mode=tooth_assignment_mode,
        )
        quadrant_assignment = assign_pathology_to_teeth_by_mode(
            pathology_boxes=pathology_boxes,
            tooth_boxes=quadrant_boxes,
            assignment_mode=quadrant_assignment_mode,
        )

        for path_idx, tooth_idx in tooth_assignment.items():
            if path_idx not in quadrant_assignment:
                continue

            path_box = pathology_boxes[path_idx]
            tooth_box = tooth_boxes[tooth_idx]
            quadrant_box = quadrant_boxes[quadrant_assignment[path_idx]]

            if path_box.cls_id not in diagnosis_id_map:
                continue

            quadrant_id = int(quadrant_box.cls_id)
            enumeration_id = int(tooth_box.cls_id)
            diagnosis_id = int(diagnosis_id_map[path_box.cls_id])

            unified_predictions.append(
                {
                    'image_id': image_id,
                    'bbox': xyxy_to_xywh(path_box),
                    'score': float(path_box.score),
                    'quadrant': quadrant_id,
                    'enumeration': enumeration_id,
                    'diagnosis': diagnosis_id,
                    'quadrant_score': float(quadrant_box.score),
                    'tooth_score': float(tooth_box.score),
                }
            )
            challenge_boxes.append(
                {
                    'name': f'{quadrant_id} - {enumeration_id} - {diagnosis_id}',
                    'corners': [
                        [float(path_box.x1), float(path_box.y1), image_id],
                        [float(path_box.x1), float(path_box.y2), image_id],
                        [float(path_box.x2), float(path_box.y1), image_id],
                        [float(path_box.x2), float(path_box.y2), image_id],
                    ],
                    'probability': float(path_box.score),
                }
            )

    print(f'{split_name} A+B+C prediction count: {len(unified_predictions)}')
    return unified_predictions, challenge_boxes


def metric_table(metrics_by_task: Dict[str, Dict[str, float]]) -> pd.DataFrame:
    aggregate = aggregate_task_metrics(metrics_by_task)
    rows = []
    for task_name in ['Quadrant', 'Enumeration', 'Diagnosis']:
        row = {'Subtask': task_name}
        row.update(metrics_by_task[task_name])
        rows.append(row)
    rows.append({'Subtask': 'Aggregate', **aggregate})
    return pd.DataFrame(rows)


def write_metrics_json(path: Path, metrics_by_task: Dict[str, Dict[str, float]]) -> None:
    aggregate = aggregate_task_metrics(metrics_by_task)
    payload = {
        'Quadrant': metrics_by_task['Quadrant'],
        'Enumeration': metrics_by_task['Enumeration'],
        'Diagnosis': metrics_by_task['Diagnosis'],
        'Aggregates': aggregate,
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding='utf-8')


TEST_DIAGNOSIS_TO_MODEL_ID = {
    1: 1,  # curuk -> caries
    6: 0,  # gomulu -> impacted
    7: 2,  # lezyon -> periapical lesion
}

TEST_DIAGNOSIS_LABEL_NAMES = {
    0: 'saglam',
    1: 'curuk',
    2: 'kuretaj',
    3: 'kanal',
    5: 'cekim',
    6: 'gomulu',
    7: 'lezyon',
    8: 'kirik',
}


def build_released_test_gt_payload(test_label_root: Path) -> dict:
    images = []
    annotations = []
    diagnosis_ids = set()
    ann_id = 1

    for json_path in sorted(test_label_root.glob('test_*.json')):
        image_id = int(json_path.stem.split('_')[-1])
        with json_path.open('r', encoding='utf-8') as file:
            payload = json.load(file)

        width = int(payload.get('imageWidth', 0))
        height = int(payload.get('imageHeight', 0))
        images.append(
            {
                'id': image_id,
                'file_name': payload.get('imagePath', f'test_{image_id}.png'),
                'width': width,
                'height': height,
            }
        )

        for shape in payload.get('shapes', []):
            label = str(shape.get('label', ''))
            parts = label.split('-')
            if len(parts) < 3:
                continue

            raw_diagnosis_id = int(parts[0])
            if raw_diagnosis_id not in TEST_DIAGNOSIS_TO_MODEL_ID:
                continue

            diagnosis_id = TEST_DIAGNOSIS_TO_MODEL_ID[raw_diagnosis_id]
            tooth_code = str(parts[2])
            if len(tooth_code) != 2 or not tooth_code.isdigit():
                continue

            quadrant_id = int(tooth_code[0]) - 1
            enumeration_id = int(tooth_code[1]) - 1
            if not (0 <= quadrant_id < 4 and 0 <= enumeration_id < 8):
                continue

            points = shape.get('points', [])
            if not points:
                continue

            xs = [float(point[0]) for point in points]
            ys = [float(point[1]) for point in points]
            x1, x2 = min(xs), max(xs)
            y1, y2 = min(ys), max(ys)
            w = max(0.0, x2 - x1)
            h = max(0.0, y2 - y1)
            if w <= 1.0 or h <= 1.0:
                continue

            annotations.append(
                {
                    'id': ann_id,
                    'image_id': image_id,
                    'bbox': [x1, y1, w, h],
                    'area': w * h,
                    'iscrowd': 0,
                    'category_id_1': quadrant_id,
                    'category_id_2': enumeration_id,
                    'category_id_3': diagnosis_id,
                }
            )
            ann_id += 1
            diagnosis_ids.add(diagnosis_id)

    return {
        'images': images,
        'annotations': annotations,
        'categories_1': [{'id': idx, 'name': str(idx)} for idx in range(4)],
        'categories_2': [{'id': idx, 'name': str(idx)} for idx in range(8)],
        'categories_3': [
            {'id': diag_id, 'name': str(diag_id)} for diag_id in sorted(diagnosis_ids)
        ],
    }


def copy_existing_file(source: Path, destination: Path) -> Path | None:
    if source.exists() and source.is_file():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        return destination
    return None


def build_download_bundle(weight_paths: List[Path]) -> Path:
    bundle_root = CFG['work_root'] / 'download_bundle'
    ensure_clean_dir(bundle_root)

    named_files_to_copy = [
        (Path(weight_paths[0]), 'pathology_best.pt'),
        (Path(weight_paths[1]), 'tooth_best.pt'),
        (Path(weight_paths[2]), 'quadrant_best.pt'),
        (CFG['pred_root'] / 'final_metrics_validation_official_style.json', 'final_metrics_validation_official_style.json'),
        (CFG['pred_root'] / 'final_metrics_released_test_official_style.json', 'final_metrics_released_test_official_style.json'),
        (CFG['pred_root'] / 'predictions_unified_validation.json', 'predictions_unified_validation.json'),
        (CFG['pred_root'] / 'predictions_challenge_format_validation.json', 'predictions_challenge_format_validation.json'),
        (CFG['pred_root'] / 'predictions_unified_test.json', 'predictions_unified_test.json'),
        (CFG['pred_root'] / 'predictions_challenge_format_test.json', 'predictions_challenge_format_test.json'),
        (CFG['pred_root'] / 'final_per_class_diagnosis_ap50.csv', 'final_per_class_diagnosis_ap50.csv'),
        (CFG['pred_root'] / 'final_per_class_enumeration_ap50.csv', 'final_per_class_enumeration_ap50.csv'),
        (CFG['pred_root'] / 'final_per_class_quadrant_ap50.csv', 'final_per_class_quadrant_ap50.csv'),
        (CFG['pred_root'] / 'final_error_decomposition_validation.csv', 'final_error_decomposition_validation.csv'),
        (CFG['pred_root'] / 'final_summary.json', 'final_summary.json'),
    ]

    copied = []
    for source, destination_name in named_files_to_copy:
        copied_path = copy_existing_file(Path(source), bundle_root / destination_name)
        if copied_path is not None:
            copied.append(copied_path)

    summary_lines = ['Download bundle files:']
    total_mb = 0.0
    for path in sorted(copied):
        size_mb = path.stat().st_size / (1024 * 1024)
        total_mb += size_mb
        summary_lines.append(f'- {path.name}: {size_mb:.2f} MB')
    summary_lines.append(f'Total bundle size: {total_mb:.2f} MB')

    summary_path = bundle_root / 'bundle_summary.txt'
    summary_path.write_text('\n'.join(summary_lines) + '\n', encoding='utf-8')

    archive_path = shutil.make_archive(str(bundle_root), 'zip', root_dir=bundle_root)
    print('Bundle created:')
    print(bundle_root)
    print(archive_path)
    print(summary_path.read_text(encoding='utf-8'))
    return Path(archive_path)


gt_validation_payload = load_gt_payload('validation')
diagnosis_id_map = diagnosis_pred_to_gt_id_map(gt_validation_payload)
validation_image_paths = (
    (CFG['yolo_root'] / 'pathology' / 'validation.txt')
    .read_text(encoding='utf-8')
    .strip()
    .splitlines()
)
file_to_image_val = {
    Path(item['file_name']).name: int(item['id']) for item in gt_validation_payload['images']
}

test_image_paths = (
    (CFG['yolo_root'] / 'pathology' / 'test.txt')
    .read_text(encoding='utf-8')
    .strip()
    .splitlines()
)
file_to_image_test = {Path(path).name: parse_test_image_id(Path(path).name) for path in test_image_paths}

if CFG['sanity_mode']:
    validation_image_paths = validation_image_paths[:CFG['sanity_max_eval_images']]
    test_image_paths = test_image_paths[:CFG['sanity_max_test_images']]

print('Diagnosis id map:', diagnosis_id_map)
print(f'Validation images used for evaluation: {len(validation_image_paths)}')
print(f'Test images used for evaluation/export: {len(test_image_paths)}')

print('=' * 80)
print('Training final Model A, Model B, and Model C')
print('=' * 80)
pathology_result, pathology_weights = train_yolo_baseline(
    model_source=FINAL_CONFIG['pathology_model'],
    run_name=f"{FINAL_CONFIG['name']}_pathology",
    data_yaml=pathology_yaml,
    exp_cfg=FINAL_CONFIG,
)
tooth_result, tooth_weights = train_yolo_baseline(
    model_source=FINAL_CONFIG['tooth_model'],
    run_name=f"{FINAL_CONFIG['name']}_tooth",
    data_yaml=tooth_yaml,
    exp_cfg=FINAL_CONFIG,
)
quadrant_result, quadrant_weights = train_yolo_baseline(
    model_source=FINAL_CONFIG['quadrant_model'],
    run_name=f"{FINAL_CONFIG['name']}_quadrant",
    data_yaml=quadrant_yaml,
    exp_cfg=FINAL_CONFIG,
)

pathology_model = YOLO(str(pathology_weights))
tooth_model = YOLO(str(tooth_weights))
quadrant_model = YOLO(str(quadrant_weights))

validation_predictions, validation_challenge_boxes = build_predictions_with_model_c(
    split_name='validation',
    image_paths=validation_image_paths,
    image_id_lookup=file_to_image_val,
    pathology_model=pathology_model,
    tooth_model=tooth_model,
    quadrant_model=quadrant_model,
    diagnosis_id_map=diagnosis_id_map,
    pathology_conf=CFG['pathology_conf'],
    tooth_conf=CFG['tooth_conf'],
    quadrant_conf=CFG['quadrant_conf'],
    predict_iou=CFG['predict_iou'],
    enable_ab_tta=FINAL_CONFIG['ab_enable_tta'],
    enable_quadrant_tta=FINAL_CONFIG['quadrant_enable_tta'],
    tooth_assignment_mode=FINAL_CONFIG['tooth_assignment_mode'],
    quadrant_assignment_mode=FINAL_CONFIG['quadrant_assignment_mode'],
)

pred_unified_val_path, pred_challenge_val_path = write_prediction_files(
    split_name='validation',
    unified_predictions=validation_predictions,
    challenge_boxes=validation_challenge_boxes,
)
print(f'Saved validation unified predictions: {pred_unified_val_path}')
print(f'Saved validation challenge-format predictions: {pred_challenge_val_path}')

validation_metrics = evaluate_all_tasks(
    gt_payload=gt_validation_payload,
    predictions=validation_predictions,
    prefix='final_validation',
)
write_metrics_json(CFG['pred_root'] / 'final_metrics_validation_official_style.json', validation_metrics)
display(metric_table(validation_metrics))

per_class_specs = [
    ('diagnosis', 'category_id_3', 'categories_3', 'final_per_class_diagnosis_ap50.csv'),
    ('enumeration', 'category_id_2', 'categories_2', 'final_per_class_enumeration_ap50.csv'),
    ('quadrant', 'category_id_1', 'categories_1', 'final_per_class_quadrant_ap50.csv'),
]
for task_name, category_field, categories_key, filename in per_class_specs:
    per_class_df = evaluate_per_class_ap50(
        gt_payload=gt_validation_payload,
        predictions=validation_predictions,
        task_name=task_name,
        category_field=category_field,
        categories_key=categories_key,
        prefix=f'final_validation_{task_name}_per_class',
    )
    per_class_df.to_csv(CFG['pred_root'] / filename, index=False)
    display(per_class_df)

error_df = error_decomposition(gt_validation_payload, validation_predictions, iou_thr=0.5)
error_df.to_csv(CFG['pred_root'] / 'final_error_decomposition_validation.csv', index=False)
display(error_df['error_type'].value_counts().rename_axis('error_type').reset_index(name='count'))

test_predictions, test_challenge_boxes = build_predictions_with_model_c(
    split_name='test',
    image_paths=test_image_paths,
    image_id_lookup=file_to_image_test,
    pathology_model=pathology_model,
    tooth_model=tooth_model,
    quadrant_model=quadrant_model,
    diagnosis_id_map=diagnosis_id_map,
    pathology_conf=CFG['pathology_conf'],
    tooth_conf=CFG['tooth_conf'],
    quadrant_conf=CFG['quadrant_conf'],
    predict_iou=CFG['predict_iou'],
    enable_ab_tta=FINAL_CONFIG['ab_enable_tta'],
    enable_quadrant_tta=FINAL_CONFIG['quadrant_enable_tta'],
    tooth_assignment_mode=FINAL_CONFIG['tooth_assignment_mode'],
    quadrant_assignment_mode=FINAL_CONFIG['quadrant_assignment_mode'],
)

pred_unified_test_path, pred_challenge_test_path = write_prediction_files(
    split_name='test',
    unified_predictions=test_predictions,
    challenge_boxes=test_challenge_boxes,
)
print(f'Saved test unified predictions: {pred_unified_test_path}')
print(f'Saved test challenge-format predictions: {pred_challenge_test_path}')

if CFG['sanity_mode']:
    print('Sanity mode active: released-test metrics and bundle creation skipped.')
else:
    released_test_label_root = split_roots['test'] / 'disease' / 'label'
    released_test_gt_payload = build_released_test_gt_payload(released_test_label_root)
    comparable_diagnosis_ids = [item['id'] for item in released_test_gt_payload['categories_3']]
    print(f'Released-test comparable annotations: {len(released_test_gt_payload["annotations"])}')
    print(f'Released-test comparable diagnosis ids: {comparable_diagnosis_ids}')
    coverage_ids = {int(item['image_id']) for item in test_predictions}
    print(f'Released-test prediction coverage: {len(coverage_ids)} / {len(released_test_gt_payload["images"])} images')

    released_test_metrics = evaluate_all_tasks(
        gt_payload=released_test_gt_payload,
        predictions=test_predictions,
        prefix='final_released_test',
    )
    write_metrics_json(
        CFG['pred_root'] / 'final_metrics_released_test_official_style.json',
        released_test_metrics,
    )
    display(metric_table(released_test_metrics))

    summary = {
        'config': FINAL_CONFIG,
        'weights': {
            'pathology': str(pathology_weights),
            'tooth': str(tooth_weights),
            'quadrant': str(quadrant_weights),
        },
        'validation_metrics': {
            **validation_metrics,
            'Aggregates': aggregate_task_metrics(validation_metrics),
        },
        'released_test_metrics': {
            **released_test_metrics,
            'Aggregates': aggregate_task_metrics(released_test_metrics),
        },
        'prediction_files': {
            'validation_unified': str(pred_unified_val_path),
            'validation_challenge': str(pred_challenge_val_path),
            'test_unified': str(pred_unified_test_path),
            'test_challenge': str(pred_challenge_test_path),
        },
    }
    write_json(CFG['pred_root'] / 'final_summary.json', summary)

    bundle_zip_path = build_download_bundle([pathology_weights, tooth_weights, quadrant_weights])

    prune_heavy_outputs([pathology_weights, tooth_weights, quadrant_weights])

print(f"Saved outputs under: {CFG['pred_root']}")

Diagnosis id map: {0: 0, 1: 1, 2: 2, 3: 3}
Validation images used for evaluation: 50
Test images used for evaluation/export: 250
================================================================================
Training final Model A, Model B, and Model C
================================================================================
Applied Ray callback compatibility patch.
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt'...

100%|██████████| 5.35M/5.35M [00:00<00:00, 71.8MB/s]

New https://pypi.org/project/ultralytics/8.4.41 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.32 🚀 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: task=detect, mode=train, model=yolo11n.pt, data=/kaggle/working/dentex_final_model_c/yolo/pathology/dataset.yaml, epochs=500, time=None, patience=30, batch=8, imgsz=1024, save=True, save_period=-1, cache=False, device=0, workers=2, project=/kaggle/working/dentex_final_model_c/runs, name=final_model_c_lower_lr_yolo11s_quadrant_pathology, exist_ok=True, pretrained=True, optimizer=AdamW, verbose=False, seed=42, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=False, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.003, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.01, hsv_s=0.15, hsv_v=0.15, degrees=8.0, translate=0.03, scale=0.15, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.0, bgr=0.0, mosaic=0.1, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_pathology
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf'...

100%|██████████| 755k/755k [00:00<00:00, 17.0MB/s]
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777202758.491763      22 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777202758.616937      22 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777202759.671096      22 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777202759.671133      22 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777202759.671136      22 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777202759.671139      22 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    431452  ultralytics.nn.modules.head.Detect           [4, [64, 128, 256]]
YOLO11n summary: 319 layers, 2,590,620 parameters, 2,590,604 gradients, 6.4 GFLOPs

Transferred 448/499 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_pathology', view at http://localhost:6006/
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

train: Scanning /kaggle/working/dentex_final_model_c/yolo/pathology/labels/train... 705 images, 27 backgrounds, 0 corrupt: 100%|██████████| 705/705 [00:15<00:00, 46.23it/s]

train: WARNING ⚠️ /kaggle/working/dentex_final_model_c/yolo/pathology/images/train/train_377.png: 1 duplicate labels removed
train: New cache created: /kaggle/working/dentex_final_model_c/yolo/pathology/labels/train.cache

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

/usr/local/lib/python3.12/dist-packages/ultralytics/data/augment.py:1850: UserWarning: Argument(s) 'quality_lower' are not valid for transform ImageCompression
  A.ImageCompression(quality_lower=75, p=0.0),
val: Scanning /kaggle/working/dentex_final_model_c/yolo/pathology/labels/validation... 50 images, 4 backgrounds, 0 corrupt: 100%|██████████| 50/50 [00:01<00:00, 48.36it/s]

val: New cache created: /kaggle/working/dentex_final_model_c/yolo/pathology/labels/validation.cache

optimizer: AdamW(lr=0.003, momentum=0.937) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 1024 train, 1024 val
Using 2 dataloader workers
Logging results to /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_pathology
Starting training for 500 epochs...
1/500      3.09G      1.525      2.717      1.582         13       1024
                   all         50        182     0.0658      0.885      0.164     0.0895
2/500      2.99G      1.343      1.972      1.395          6       1024
                   all         50        182       0.72      0.353      0.283      0.169
3/500      3.01G      1.306       1.84       1.37          6       1024
                   all         50        182      0.743      0.313      0.283      0.152
4/500      3.01G      1.307        1.8      1.384          2       1024
                   all         50        182      0.501      0.357      0.284      0.161
5/500      3.03G      1.279       1.74      1.338         10       1024
                   all         50        182       0.69       0.32      0.317      0.179
6/500      3.02G       1.24      1.697      1.326          4       1024
                   all         50        182      0.479      0.328      0.288      0.173
7/500      3.01G      1.254      1.691      1.323          1       1024
                   all         50        182      0.502      0.371      0.317      0.174
8/500      3.01G      1.259      1.661      1.328         10       1024
                   all         50        182      0.252       0.52      0.317      0.177
9/500      3.02G      1.206      1.612      1.296          2       1024
                   all         50        182      0.516      0.409      0.311      0.179
10/500      3.02G      1.199      1.565      1.292          6       1024
                   all         50        182      0.384      0.508      0.382      0.215
11/500      2.98G      1.177      1.562      1.272          3       1024
                   all         50        182      0.306      0.396      0.304      0.175
12/500         3G      1.157      1.531      1.273          7       1024
                   all         50        182      0.475      0.534      0.385      0.228
13/500      3.03G      1.147      1.508      1.262          6       1024
                   all         50        182      0.306      0.451       0.38      0.222
14/500      3.02G       1.16       1.52      1.277          4       1024
                   all         50        182      0.564      0.501        0.4      0.209
15/500         3G      1.151      1.469      1.256          9       1024
                   all         50        182      0.379      0.479      0.406       0.23
16/500      3.06G      1.155      1.459      1.253          8       1024
                   all         50        182      0.573      0.513      0.409      0.248
17/500      3.04G      1.146      1.467       1.25          7       1024
                   all         50        182      0.543        0.5      0.429      0.231
18/500      3.06G      1.127      1.422      1.228          2       1024
                   all         50        182      0.401      0.487      0.381      0.219
19/500      3.04G      1.103      1.438      1.222         10       1024
                   all         50        182      0.445       0.53      0.411      0.242
20/500      3.03G      1.123      1.396      1.232          8       1024
                   all         50        182      0.561      0.474      0.376      0.231
21/500      3.03G      1.083      1.389      1.216          6       1024
                   all         50        182      0.384      0.397      0.369      0.228
22/500      3.03G      1.075       1.37      1.208          3       1024
                   all         50        182      0.386      0.551      0.419      0.247
23/500      3.02G      1.063      1.361      1.203         11       1024
                   all         50        182      0.346      0.474      0.381       0.23
24/500      3.03G      1.083      1.335      1.215          7       1024
                   all         50        182      0.309      0.527      0.414      0.253
25/500      3.02G      1.104      1.394      1.225          1       1024
                   all         50        182      0.421      0.481      0.429      0.231
26/500      3.02G      1.073      1.354      1.206          2       1024
                   all         50        182      0.523      0.568      0.461      0.276
27/500      3.04G      1.045      1.326      1.197          7       1024
                   all         50        182      0.445      0.554      0.414      0.256
28/500      3.03G      1.033      1.278      1.184         12       1024
                   all         50        182      0.446      0.542      0.455       0.28
29/500      3.02G      1.058      1.301        1.2          5       1024
                   all         50        182      0.421      0.518      0.408      0.244
30/500      3.04G      1.053      1.288      1.195          2       1024
                   all         50        182      0.459      0.566      0.437      0.261
31/500      3.07G      1.034      1.242       1.19          9       1024
                   all         50        182      0.349      0.572      0.411       0.25
32/500      3.03G      1.025      1.246      1.182          5       1024
                   all         50        182      0.598       0.42      0.403      0.239
33/500      3.05G      1.034      1.216      1.181         23       1024
                   all         50        182      0.448      0.545      0.482      0.299
34/500         3G      1.034      1.207      1.183          7       1024
                   all         50        182      0.309       0.58      0.397      0.254
35/500      3.08G      1.011      1.243      1.167         10       1024
                   all         50        182      0.439      0.445      0.424      0.263
36/500      3.02G     0.9905      1.212      1.147         11       1024
                   all         50        182      0.474      0.603      0.522      0.319
37/500      3.01G     0.9854       1.15      1.158          3       1024
                   all         50        182      0.487      0.684      0.523       0.32
38/500      3.04G     0.9664      1.281       1.13          0       1024
                   all         50        182      0.505      0.582       0.48      0.289
39/500      3.02G      0.968      1.147       1.14          4       1024
                   all         50        182      0.434      0.563      0.468      0.294
40/500         3G     0.9665      1.138      1.137          3       1024
                   all         50        182      0.394      0.542      0.444      0.277
41/500      3.03G     0.9624      1.131      1.132          6       1024
                   all         50        182      0.477      0.467       0.44      0.271
42/500         3G     0.9632      1.125      1.127          8       1024
                   all         50        182      0.522      0.534      0.478      0.298
43/500         3G      0.955      1.129      1.125          1       1024
                   all         50        182      0.408      0.508      0.406       0.25
44/500      3.02G     0.9476      1.114       1.12         16       1024
                   all         50        182       0.53       0.48      0.456      0.283
45/500      3.01G     0.9669      1.083      1.135          4       1024
                   all         50        182      0.497      0.426      0.393      0.234
46/500      3.02G     0.9392      1.081      1.119          7       1024
                   all         50        182      0.596      0.436      0.451      0.274
47/500      3.02G     0.9492      1.088      1.121          5       1024
                   all         50        182      0.599       0.44      0.427      0.257
48/500      3.04G     0.9361      1.063      1.114          2       1024
                   all         50        182      0.492      0.415      0.414      0.262
49/500      3.05G     0.9191      1.023      1.104          6       1024
                   all         50        182      0.453       0.57      0.443      0.264
50/500      2.99G     0.9305      1.036      1.107          4       1024
                   all         50        182      0.459      0.525      0.427       0.26
51/500      3.02G     0.9224      1.022      1.098          5       1024
                   all         50        182      0.416      0.545      0.469      0.285
52/500      3.03G     0.9063      1.004      1.089          4       1024
                   all         50        182      0.512      0.501       0.46      0.282
53/500         3G     0.9101     0.9804      1.096          7       1024
                   all         50        182      0.451      0.598      0.477      0.313
54/500      3.08G     0.8948     0.9847      1.082          3       1024
                   all         50        182      0.503      0.549       0.44      0.264
55/500      3.04G     0.9115     0.9724      1.089          9       1024
                   all         50        182      0.516      0.506      0.436      0.272
56/500      2.99G     0.9184     0.9589      1.098          8       1024
                   all         50        182      0.535       0.56      0.472      0.295
57/500      3.09G     0.8991     0.9718       1.08          2       1024
                   all         50        182        0.5      0.509      0.452      0.271
58/500      3.02G     0.8681     0.9346      1.064          1       1024
                   all         50        182      0.468      0.514      0.442      0.279
59/500      2.99G     0.8645     0.9078      1.059          7       1024
                   all         50        182      0.531      0.534      0.467      0.282
60/500      3.07G     0.8846     0.9019      1.074         10       1024
                   all         50        182      0.471      0.505      0.448      0.282
61/500      3.04G     0.8984      0.913      1.079          3       1024
                   all         50        182      0.414      0.591      0.449      0.274
62/500         3G     0.8727     0.8938      1.065          5       1024
                   all         50        182      0.524      0.461      0.451      0.279
63/500      3.04G     0.8552     0.8777      1.058          5       1024
                   all         50        182      0.536      0.478      0.424      0.267
64/500      3.01G      0.834      0.855      1.037          6       1024
                   all         50        182      0.475      0.507      0.446      0.269
65/500      3.03G     0.8302      0.905      1.036          0       1024
                   all         50        182      0.537      0.431      0.425      0.262
66/500      3.04G     0.8397     0.8327      1.048          2       1024
                   all         50        182      0.569       0.48       0.49      0.287
67/500      3.02G     0.8391      0.846      1.046          4       1024
                   all         50        182      0.474      0.475       0.41      0.252
EarlyStopping: Training stopped early as no improvement observed in last 30 epochs. Best results observed at epoch 37, best model saved as best.pt.
To update EarlyStopping(patience=30) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

67 epochs completed in 0.746 hours.
Optimizer stripped from /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_pathology/weights/last.pt, 5.5MB
Optimizer stripped from /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_pathology/weights/best.pt, 5.5MB

Validating /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_pathology/weights/best.pt...
Ultralytics 8.3.32 🚀 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11n summary (fused): 238 layers, 2,582,932 parameters, 0 gradients, 6.3 GFLOPs
                   all         50        182      0.488      0.684      0.522       0.32
Speed: 0.3ms preprocess, 3.0ms inference, 0.0ms loss, 1.0ms postprocess per image
Run: final_model_c_lower_lr_yolo11s_quadrant_pathology
Elapsed seconds: 2742.03
Best weights: /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_pathology/weights/best.pt
New https://pypi.org/project/ultralytics/8.4.41 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.32 🚀 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: task=detect, mode=train, model=yolo11n.pt, data=/kaggle/working/dentex_final_model_c/yolo/tooth_enumeration/dataset.yaml, epochs=500, time=None, patience=30, batch=8, imgsz=1024, save=True, save_period=-1, cache=False, device=0, workers=2, project=/kaggle/working/dentex_final_model_c/runs, name=final_model_c_lower_lr_yolo11s_quadrant_tooth, exist_ok=True, pretrained=True, optimizer=AdamW, verbose=False, seed=42, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=False, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.003, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.01, hsv_s=0.15, hsv_v=0.15, degrees=8.0, translate=0.03, scale=0.15, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.0, bgr=0.0, mosaic=0.1, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_tooth
Overriding model.yaml nc=80 with nc=8

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    432232  ultralytics.nn.modules.head.Detect           [8, [64, 128, 256]]
YOLO11n summary: 319 layers, 2,591,400 parameters, 2,591,384 gradients, 6.4 GFLOPs

Transferred 448/499 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_tooth', view at http://localhost:6006/
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

train: Scanning /kaggle/working/dentex_final_model_c/yolo/tooth_enumeration/labels/train... 705 images, 27 backgrounds, 0 corrupt: 100%|██████████| 705/705 [00:15<00:00, 46.85it/s]

train: WARNING ⚠️ /kaggle/working/dentex_final_model_c/yolo/tooth_enumeration/images/train/train_280.png: 1 duplicate labels removed
train: WARNING ⚠️ /kaggle/working/dentex_final_model_c/yolo/tooth_enumeration/images/train/train_377.png: 1 duplicate labels removed
train: WARNING ⚠️ /kaggle/working/dentex_final_model_c/yolo/tooth_enumeration/images/train/train_481.png: 1 duplicate labels removed
train: New cache created: /kaggle/working/dentex_final_model_c/yolo/tooth_enumeration/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

/usr/local/lib/python3.12/dist-packages/ultralytics/data/augment.py:1850: UserWarning: Argument(s) 'quality_lower' are not valid for transform ImageCompression
  A.ImageCompression(quality_lower=75, p=0.0),
val: Scanning /kaggle/working/dentex_final_model_c/yolo/tooth_enumeration/labels/validation... 50 images, 4 backgrounds, 0 corrupt: 100%|██████████| 50/50 [00:00<00:00, 60.95it/s]

val: New cache created: /kaggle/working/dentex_final_model_c/yolo/tooth_enumeration/labels/validation.cache

optimizer: AdamW(lr=0.003, momentum=0.937) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 1024 train, 1024 val
Using 2 dataloader workers
Logging results to /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_tooth
Starting training for 500 epochs...
1/500      3.11G      1.553      3.063      1.484         13       1024
                   all         50        182       0.13      0.147      0.135     0.0758
2/500      3.01G      1.383      1.987      1.331          6       1024
                   all         50        182      0.489      0.288      0.171        0.1
3/500      3.02G      1.354      1.861      1.315          6       1024
                   all         50        182      0.641      0.245      0.166     0.0873
4/500      3.02G      1.351      1.733      1.318          2       1024
                   all         50        182      0.517      0.245      0.178      0.106
5/500      3.03G      1.314      1.695      1.285         10       1024
                   all         50        182      0.516       0.34      0.206      0.112
6/500      3.09G      1.262      1.632      1.258          4       1024
                   all         50        182      0.643      0.247       0.18      0.107
7/500      3.02G      1.258      1.607      1.238          1       1024
                   all         50        182      0.558      0.268      0.207      0.122
8/500      3.09G      1.267      1.531      1.238         10       1024
                   all         50        182      0.439        0.3      0.234      0.139
9/500      3.02G      1.244      1.513      1.236          2       1024
                   all         50        182      0.547      0.338       0.22      0.124
10/500      3.02G      1.218      1.468      1.224          6       1024
                   all         50        182       0.56      0.248      0.238       0.15
11/500      2.99G      1.217      1.454      1.208          3       1024
                   all         50        182      0.336      0.322      0.232      0.136
12/500      3.01G      1.212       1.44      1.197          7       1024
                   all         50        182      0.436      0.479      0.251      0.151
13/500      3.05G      1.193      1.397      1.198          6       1024
                   all         50        182      0.434      0.311      0.273      0.161
14/500      3.02G       1.22       1.43      1.214          4       1024
                   all         50        182      0.655      0.319      0.282      0.172
15/500      3.02G      1.175      1.398      1.184          9       1024
                   all         50        182      0.582      0.319      0.275      0.167
16/500      3.08G      1.208      1.336      1.194          8       1024
                   all         50        182      0.182      0.337       0.27      0.166
17/500      3.05G      1.193      1.369      1.192          7       1024
                   all         50        182      0.471      0.369      0.269      0.145
18/500      3.08G      1.183      1.345      1.184          2       1024
                   all         50        182      0.453      0.269      0.287      0.152
19/500      3.05G      1.167      1.336      1.181         10       1024
                   all         50        182      0.651      0.251      0.307      0.167
20/500      3.03G      1.162      1.296      1.173          8       1024
                   all         50        182      0.624      0.305      0.308      0.176
21/500      3.03G       1.15      1.275      1.165          6       1024
                   all         50        182        0.5      0.258      0.273      0.143
22/500      3.05G      1.156      1.285      1.173          3       1024
                   all         50        182      0.329       0.34      0.288      0.174
23/500      3.03G      1.138      1.272      1.165         11       1024
                   all         50        182      0.472      0.355      0.322      0.177
24/500      3.05G      1.155      1.234      1.168          7       1024
                   all         50        182      0.562      0.396      0.289      0.178
25/500      3.02G       1.16      1.278      1.161          1       1024
                   all         50        182      0.498      0.327      0.289      0.172
26/500      3.02G      1.133       1.23      1.159          2       1024
                   all         50        182      0.497      0.335      0.292      0.172
27/500      3.06G      1.121      1.209      1.145          7       1024
                   all         50        182      0.364      0.397      0.326      0.204
28/500      3.03G      1.109      1.173      1.134         12       1024
                   all         50        182      0.239      0.394       0.31      0.183
29/500      3.02G      1.116      1.175      1.139          5       1024
                   all         50        182      0.689      0.298      0.311      0.186
30/500      3.06G      1.102      1.182      1.139          2       1024
                   all         50        182      0.414      0.263      0.301      0.177
31/500      3.08G      1.106       1.14      1.131          9       1024
                   all         50        182      0.341      0.381      0.297      0.181
32/500      3.03G       1.11      1.162      1.139          5       1024
                   all         50        182      0.546      0.314        0.3      0.158
33/500      3.06G      1.115      1.126      1.134         23       1024
                   all         50        182      0.322      0.323      0.342      0.204
34/500      3.02G      1.084      1.096      1.124          7       1024
                   all         50        182      0.383      0.367      0.327      0.175
35/500      3.09G       1.07      1.133      1.115         10       1024
                   all         50        182      0.559      0.379       0.39      0.219
36/500      3.02G      1.053      1.112      1.108         11       1024
                   all         50        182      0.698      0.325      0.346      0.201
37/500      3.02G      1.048      1.077      1.107          3       1024
                   all         50        182       0.63      0.269       0.34      0.216
38/500      3.06G      1.034       1.24      1.091          0       1024
                   all         50        182      0.464      0.379      0.355      0.212
39/500      3.09G      1.017       1.06      1.093          4       1024
                   all         50        182      0.525      0.307      0.355      0.217
40/500      3.01G      1.024      1.041      1.094          3       1024
                   all         50        182      0.381      0.389       0.39      0.232
41/500      3.05G     0.9988          1      1.075          6       1024
                   all         50        182       0.47      0.422       0.38      0.179
42/500      3.01G      1.011      1.015      1.081          8       1024
                   all         50        182      0.463      0.404      0.386      0.238
43/500      3.01G       1.01      1.034      1.085          1       1024
                   all         50        182      0.596      0.274      0.341      0.214
44/500      3.02G      1.016      1.051      1.084         16       1024
                   all         50        182      0.281      0.392      0.337      0.203
45/500      3.02G     0.9937     0.9999      1.082          4       1024
                   all         50        182      0.338      0.404      0.383      0.234
46/500      3.02G     0.9943      1.013       1.08          7       1024
                   all         50        182      0.303      0.369      0.373      0.197
47/500      3.02G      0.981      1.024      1.067          5       1024
                   all         50        182      0.406      0.373      0.339      0.196
48/500      3.06G      0.953     0.9705      1.064          2       1024
                   all         50        182      0.249      0.401      0.345      0.207
49/500      3.07G     0.9705     0.9344      1.073          6       1024
                   all         50        182      0.263      0.563      0.381      0.229
50/500      3.01G     0.9742     0.9443      1.067          4       1024
                   all         50        182       0.49      0.352      0.365      0.207
51/500      3.02G     0.9615     0.9417      1.055          5       1024
                   all         50        182      0.344      0.368      0.373       0.24
52/500      3.03G     0.9476     0.9256      1.052          4       1024
                   all         50        182      0.357       0.48      0.402      0.225
53/500      3.01G     0.9414     0.9028      1.048          7       1024
                   all         50        182      0.354      0.491      0.419      0.244
54/500      3.09G     0.9397     0.9068      1.047          3       1024
                   all         50        182      0.368      0.401      0.397       0.24
55/500      3.06G     0.9417     0.9079      1.045          9       1024
                   all         50        182      0.498      0.368      0.352      0.196
56/500      3.01G     0.9393     0.9078      1.045          8       1024
                   all         50        182      0.493      0.347      0.341      0.206
57/500      3.09G     0.9158     0.9094      1.038          2       1024
                   all         50        182       0.48      0.401      0.379      0.235
58/500      3.02G     0.9237     0.8859       1.04          1       1024
                   all         50        182      0.293      0.476      0.396      0.252
59/500      3.01G     0.9086     0.8581      1.035          7       1024
                   all         50        182      0.395      0.402      0.325      0.213
60/500      3.07G      0.909     0.8329      1.028         10       1024
                   all         50        182      0.352      0.372      0.371      0.242
61/500      3.06G     0.9198     0.8365      1.032          3       1024
                   all         50        182        0.5      0.284       0.34      0.213
62/500      3.02G      0.907     0.8389      1.031          5       1024
                   all         50        182      0.301      0.451      0.363      0.218
63/500      3.05G     0.8925     0.8247      1.021          5       1024
                   all         50        182      0.537      0.347      0.401      0.222
64/500      3.01G     0.8647     0.8055      1.008          6       1024
                   all         50        182      0.386      0.435      0.356      0.223
65/500      3.05G     0.8745     0.8779      1.006          0       1024
                   all         50        182      0.296      0.413      0.341      0.216
66/500      3.05G     0.8725     0.8116      1.016          2       1024
                   all         50        182      0.293       0.49       0.37      0.218
67/500      3.02G     0.8647     0.7838      1.003          4       1024
                   all         50        182      0.611      0.358       0.37      0.218
68/500      3.02G     0.8705     0.7833      1.007          3       1024
                   all         50        182      0.531      0.402      0.364      0.221
69/500      3.03G     0.8855     0.7786      1.017          1       1024
                   all         50        182      0.312       0.37      0.339      0.205
70/500      3.02G      0.869     0.7587       1.01          4       1024
                   all         50        182       0.31      0.457      0.372      0.239
71/500      3.06G       0.85     0.7532      1.005          3       1024
                   all         50        182      0.245      0.528      0.332      0.199
72/500      3.01G      0.857     0.7403      1.005          8       1024
                   all         50        182      0.322      0.449      0.363      0.224
73/500      3.05G     0.8676      0.753      1.009          6       1024
                   all         50        182      0.423      0.309      0.363      0.228
74/500      3.05G     0.8404       0.73     0.9953          9       1024
                   all         50        182      0.393       0.42      0.404      0.238
75/500      3.02G     0.8407     0.7145     0.9975          4       1024
                   all         50        182      0.308      0.384      0.365      0.225
76/500      3.09G     0.8151     0.7062     0.9848          3       1024
                   all         50        182      0.273       0.55      0.355      0.213
77/500      3.02G     0.8288     0.6989     0.9825          8       1024
                   all         50        182      0.296      0.434      0.346      0.213
78/500      3.02G     0.8214     0.6946     0.9981          2       1024
                   all         50        182      0.368      0.358      0.367      0.229
79/500      3.02G     0.8414     0.6754     0.9926          8       1024
                   all         50        182      0.457      0.359      0.346      0.213
80/500      3.01G     0.8197     0.6761      0.987         12       1024
                   all         50        182      0.313      0.345      0.315      0.197
81/500      3.06G     0.8166     0.6957     0.9841          5       1024
                   all         50        182      0.495      0.408      0.366      0.237
82/500      3.02G     0.8093      0.679     0.9825          5       1024
                   all         50        182      0.646      0.303      0.367       0.23
83/500      3.02G     0.7962     0.6836     0.9723          2       1024
                   all         50        182      0.395       0.46      0.386      0.231
84/500      3.05G     0.8105     0.6602     0.9797          5       1024
                   all         50        182      0.274      0.481      0.334      0.213
85/500      3.02G     0.8164     0.6461     0.9802          3       1024
                   all         50        182      0.716      0.312      0.345       0.22
86/500      3.02G     0.7829     0.6402     0.9682          6       1024
                   all         50        182      0.433      0.344      0.373      0.223
87/500       3.1G     0.8137     0.6653      0.986          5       1024
                   all         50        182      0.713      0.324      0.375      0.235
88/500      3.01G     0.8134     0.6431     0.9815         13       1024
                   all         50        182       0.54      0.371      0.372      0.222
EarlyStopping: Training stopped early as no improvement observed in last 30 epochs. Best results observed at epoch 58, best model saved as best.pt.
To update EarlyStopping(patience=30) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

88 epochs completed in 0.973 hours.
Optimizer stripped from /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_tooth/weights/last.pt, 5.5MB
Optimizer stripped from /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_tooth/weights/best.pt, 5.5MB

Validating /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_tooth/weights/best.pt...
Ultralytics 8.3.32 🚀 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11n summary (fused): 238 layers, 2,583,712 parameters, 0 gradients, 6.3 GFLOPs
                   all         50        182      0.293      0.477      0.397      0.251
Speed: 0.3ms preprocess, 2.9ms inference, 0.0ms loss, 1.0ms postprocess per image
Run: final_model_c_lower_lr_yolo11s_quadrant_tooth
Elapsed seconds: 3522.42
Best weights: /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_tooth/weights/best.pt
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11s.pt to 'yolo11s.pt'...

100%|██████████| 18.4M/18.4M [00:00<00:00, 130MB/s]

New https://pypi.org/project/ultralytics/8.4.41 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.32 🚀 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: task=detect, mode=train, model=yolo11s.pt, data=/kaggle/working/dentex_final_model_c/yolo/quadrant/dataset.yaml, epochs=500, time=None, patience=30, batch=8, imgsz=1024, save=True, save_period=-1, cache=False, device=0, workers=2, project=/kaggle/working/dentex_final_model_c/runs, name=final_model_c_lower_lr_yolo11s_quadrant_quadrant, exist_ok=True, pretrained=True, optimizer=AdamW, verbose=False, seed=42, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=False, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.003, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.01, hsv_s=0.15, hsv_v=0.15, degrees=8.0, translate=0.03, scale=0.15, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.0, bgr=0.0, mosaic=0.1, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_quadrant
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    820956  ultralytics.nn.modules.head.Detect           [4, [128, 256, 512]]
YOLO11s summary: 319 layers, 9,429,340 parameters, 9,429,324 gradients, 21.6 GFLOPs

Transferred 493/499 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_quadrant', view at http://localhost:6006/
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

train: Scanning /kaggle/working/dentex_final_model_c/yolo/quadrant/labels/train... 705 images, 27 backgrounds, 0 corrupt: 100%|██████████| 705/705 [00:15<00:00, 45.78it/s]

train: WARNING ⚠️ /kaggle/working/dentex_final_model_c/yolo/quadrant/images/train/train_280.png: 1 duplicate labels removed
train: WARNING ⚠️ /kaggle/working/dentex_final_model_c/yolo/quadrant/images/train/train_377.png: 1 duplicate labels removed
train: WARNING ⚠️ /kaggle/working/dentex_final_model_c/yolo/quadrant/images/train/train_481.png: 1 duplicate labels removed
train: New cache created: /kaggle/working/dentex_final_model_c/yolo/quadrant/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

/usr/local/lib/python3.12/dist-packages/ultralytics/data/augment.py:1850: UserWarning: Argument(s) 'quality_lower' are not valid for transform ImageCompression
  A.ImageCompression(quality_lower=75, p=0.0),
val: Scanning /kaggle/working/dentex_final_model_c/yolo/quadrant/labels/validation... 50 images, 4 backgrounds, 0 corrupt: 100%|██████████| 50/50 [00:01<00:00, 46.02it/s]

val: New cache created: /kaggle/working/dentex_final_model_c/yolo/quadrant/labels/validation.cache

optimizer: AdamW(lr=0.003, momentum=0.937) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 1024 train, 1024 val
Using 2 dataloader workers
Logging results to /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_quadrant
Starting training for 500 epochs...
1/500      5.86G      1.593      2.342      1.572         13       1024
                   all         50        182       0.25       0.66      0.357      0.195
2/500      5.74G      1.383      1.612      1.382          6       1024
                   all         50        182      0.296      0.439      0.418      0.233
3/500      5.76G      1.332      1.513      1.354          6       1024
                   all         50        182      0.336      0.624      0.398      0.217
4/500      5.76G      1.342      1.502       1.36          2       1024
                   all         50        182      0.301      0.604      0.374      0.214
5/500      5.77G      1.298      1.447      1.328         10       1024
                   all         50        182      0.296      0.655      0.419      0.219
6/500      5.77G      1.278      1.421      1.313          4       1024
                   all         50        182      0.365      0.689      0.459      0.263
7/500      5.76G      1.274      1.412      1.307          1       1024
                   all         50        182      0.346      0.734      0.456      0.252
8/500      5.73G      1.281      1.368      1.299         10       1024
                   all         50        182      0.347      0.689      0.459      0.265
9/500      5.77G      1.259      1.367        1.3          2       1024
                   all         50        182      0.387      0.627      0.476      0.262
10/500      5.77G      1.215      1.306      1.275          6       1024
                   all         50        182      0.539      0.549      0.557      0.335
11/500      5.73G       1.22      1.286      1.278          3       1024
                   all         50        182      0.445      0.599      0.502      0.288
12/500      5.74G      1.208      1.271      1.264          7       1024
                   all         50        182      0.471      0.634      0.549      0.322
13/500      5.79G      1.208      1.245      1.268          6       1024
                   all         50        182       0.43      0.573      0.504      0.297
14/500      5.76G      1.211      1.244      1.268          4       1024
                   all         50        182      0.552      0.521      0.551      0.298
15/500      5.74G      1.178      1.213      1.248          9       1024
                   all         50        182      0.535      0.491      0.536      0.308
16/500      5.69G      1.195       1.19      1.254          8       1024
                   all         50        182      0.527       0.61      0.582       0.33
17/500      5.79G      1.169      1.184      1.237          7       1024
                   all         50        182      0.552      0.617      0.569      0.303
18/500      5.77G      1.165      1.171      1.236          2       1024
                   all         50        182      0.609      0.611      0.618      0.342
19/500       5.8G       1.17       1.16      1.243         10       1024
                   all         50        182      0.468      0.692      0.599      0.349
20/500      5.77G      1.155      1.143      1.236          8       1024
                   all         50        182      0.515      0.628       0.62      0.377
21/500      5.77G      1.141      1.111      1.223          6       1024
                   all         50        182      0.547      0.608      0.602      0.332
22/500      5.79G       1.14      1.097      1.221          3       1024
                   all         50        182      0.512      0.596       0.58      0.326
23/500      5.77G       1.13      1.123      1.223         11       1024
                   all         50        182      0.639      0.551      0.617      0.348
24/500      5.76G      1.148      1.094      1.224          7       1024
                   all         50        182      0.528      0.648      0.583       0.32
25/500      5.76G      1.141      1.141      1.221          1       1024
                   all         50        182      0.565      0.614      0.597      0.329
26/500      5.76G      1.129      1.104      1.235          2       1024
                   all         50        182      0.544      0.634      0.611      0.353
27/500       5.8G      1.116      1.053      1.207          7       1024
                   all         50        182      0.506      0.592      0.592      0.349
28/500      5.77G      1.093      1.026      1.191         12       1024
                   all         50        182      0.529      0.682      0.624      0.355
29/500      5.77G      1.119      1.042      1.205          5       1024
                   all         50        182      0.553      0.556      0.587      0.328
30/500       5.8G      1.089      1.031      1.193          2       1024
                   all         50        182      0.608      0.589      0.619      0.355
31/500      5.74G      1.085     0.9964      1.186          9       1024
                   all         50        182      0.527      0.636      0.597       0.35
32/500      5.75G      1.078     0.9994       1.18          5       1024
                   all         50        182       0.56      0.662      0.628      0.366
33/500       5.8G      1.083     0.9971       1.18         23       1024
                   all         50        182       0.58      0.611      0.637      0.376
34/500      5.74G      1.045     0.9653      1.168          7       1024
                   all         50        182       0.65      0.554      0.627      0.368
35/500      5.74G      1.048     0.9934      1.163         10       1024
                   all         50        182      0.516      0.681      0.618      0.377
36/500      5.77G      1.048     0.9391      1.156         11       1024
                   all         50        182      0.583      0.588      0.622      0.353
37/500      5.76G      1.042     0.9407       1.16          3       1024
                   all         50        182      0.643      0.462      0.553      0.335
38/500      5.79G      0.996      1.085       1.12          0       1024
                   all         50        182      0.672      0.543      0.658      0.388
39/500      5.76G     0.9996      0.921      1.142          4       1024
                   all         50        182      0.543      0.594      0.599      0.373
40/500      5.72G     0.9998     0.9049       1.13          3       1024
                   all         50        182      0.551      0.592      0.582      0.364
41/500       5.8G     0.9771     0.8802      1.121          6       1024
                   all         50        182      0.541      0.615      0.603      0.342
42/500      5.73G     0.9852     0.8959      1.125          8       1024
                   all         50        182      0.573      0.657      0.603      0.392
43/500      5.73G     0.9771     0.9231      1.117          1       1024
                   all         50        182      0.554      0.574      0.575      0.365
44/500      5.77G     0.9531     0.8833      1.103         16       1024
                   all         50        182      0.541      0.649      0.615      0.396
45/500      5.75G     0.9373     0.8632      1.109          4       1024
                   all         50        182      0.558      0.588      0.606      0.377
46/500      5.76G     0.9288     0.8362      1.102          7       1024
                   all         50        182      0.587      0.575      0.568      0.364
47/500      5.77G     0.9239     0.8583      1.086          5       1024
                   all         50        182      0.611      0.561      0.595       0.38
48/500      5.76G     0.9121     0.8221      1.093          2       1024
                   all         50        182      0.616       0.51      0.564      0.352
49/500       5.8G     0.9031     0.8027      1.085          6       1024
                   all         50        182      0.554       0.64      0.643      0.408
50/500      5.74G     0.9005     0.8082      1.075          4       1024
                   all         50        182      0.612      0.554      0.599      0.383
51/500      5.76G     0.8959     0.7891      1.073          5       1024
                   all         50        182       0.67      0.531      0.591      0.365
52/500      5.77G     0.8762     0.7625      1.063          4       1024
                   all         50        182      0.541       0.61        0.6      0.384
53/500      5.73G     0.8605     0.7458      1.058          7       1024
                   all         50        182      0.669      0.523      0.623      0.378
54/500      5.76G     0.8442     0.7438      1.045          3       1024
                   all         50        182      0.612      0.574      0.591      0.378
55/500      5.79G     0.8502     0.7261      1.052          9       1024
                   all         50        182      0.529       0.69      0.595      0.377
56/500       5.7G     0.8436     0.6954      1.048          8       1024
                   all         50        182      0.525      0.652       0.57      0.381
57/500      5.76G     0.8319     0.7094       1.04          2       1024
                   all         50        182      0.546      0.591      0.563      0.381
58/500      5.77G     0.8319      0.695      1.041          1       1024
                   all         50        182      0.508      0.654      0.562      0.349
59/500      5.74G      0.817     0.6843       1.03          7       1024
                   all         50        182      0.573      0.605      0.612      0.409
60/500      5.74G     0.8045     0.6798      1.024         10       1024
                   all         50        182      0.487      0.637       0.55      0.365
61/500      5.79G       0.81     0.6867      1.022          3       1024
                   all         50        182      0.572      0.582      0.556      0.373
62/500      5.73G        0.8     0.6569      1.019          5       1024
                   all         50        182      0.523      0.638      0.573      0.369
63/500      5.79G      0.783     0.6505       1.01          5       1024
                   all         50        182      0.577      0.603      0.581      0.375
64/500      5.72G     0.7794     0.6371      1.002          6       1024
                   all         50        182      0.546      0.579      0.577      0.371
65/500      5.79G     0.7665     0.7201      0.999          0       1024
                   all         50        182      0.605      0.519      0.561      0.358
66/500      5.79G     0.7519     0.6215     0.9995          2       1024
                   all         50        182      0.513      0.629       0.57      0.375
67/500      5.77G     0.7365     0.5927      0.988          4       1024
                   all         50        182      0.519      0.662      0.587      0.383
68/500      5.77G     0.7396     0.5993     0.9837          3       1024
                   all         50        182      0.597      0.579      0.538      0.354
69/500      5.77G     0.7523     0.6047     0.9976          1       1024
                   all         50        182      0.536      0.621      0.543      0.351
70/500      5.73G     0.7358     0.5792     0.9907          4       1024
                   all         50        182      0.549      0.652      0.554      0.364
71/500      5.79G     0.7336     0.5865     0.9869          3       1024
                   all         50        182      0.547       0.58      0.565      0.365
72/500      5.72G      0.736     0.5863     0.9922          8       1024
                   all         50        182      0.578      0.597      0.576      0.363
73/500      5.79G     0.7474     0.5747     0.9953          6       1024
                   all         50        182      0.593      0.565      0.563      0.376
74/500       5.8G     0.7208     0.5432     0.9751          9       1024
                   all         50        182      0.509      0.666      0.549      0.363
75/500      5.78G     0.7237     0.5551     0.9779          4       1024
                   all         50        182      0.533      0.585      0.509      0.346
76/500      5.76G     0.6984     0.5397     0.9669          3       1024
                   all         50        182      0.551       0.59      0.585      0.391
77/500      5.74G     0.7021     0.5408     0.9642          8       1024
                   all         50        182       0.63       0.51       0.59      0.387
78/500      5.76G     0.6724     0.5253      0.958          2       1024
                   all         50        182      0.493      0.689      0.566      0.379
79/500      5.77G     0.6953     0.5182     0.9624          8       1024
                   all         50        182      0.541      0.577      0.548      0.359
EarlyStopping: Training stopped early as no improvement observed in last 30 epochs. Best results observed at epoch 49, best model saved as best.pt.
To update EarlyStopping(patience=30) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

79 epochs completed in 0.929 hours.
Optimizer stripped from /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_quadrant/weights/last.pt, 19.2MB
Optimizer stripped from /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_quadrant/weights/best.pt, 19.2MB

Validating /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_quadrant/weights/best.pt...
Ultralytics 8.3.32 🚀 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11s summary (fused): 238 layers, 9,414,348 parameters, 0 gradients, 21.3 GFLOPs
                   all         50        182      0.551      0.637      0.643      0.408
Speed: 0.2ms preprocess, 6.1ms inference, 0.0ms loss, 1.0ms postprocess per image
Run: final_model_c_lower_lr_yolo11s_quadrant_quadrant
Elapsed seconds: 3363.74
Best weights: /kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_quadrant/weights/best.pt
validation A+B+C prediction count: 516
Saved validation unified predictions: /kaggle/working/dentex_final_model_c/predictions/predictions_unified_validation.json
Saved validation challenge-format predictions: /kaggle/working/dentex_final_model_c/predictions/predictions_challenge_format_validation.json
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!

       Subtask        AP      AP50      AP75        AR
0     Quadrant  0.331713  0.533471  0.390408  0.563137
1  Enumeration  0.194060  0.337465  0.183727  0.316972
2    Diagnosis  0.280027  0.480296  0.284100  0.469199
3    Aggregate  0.268600  0.450411  0.286078  0.449769

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!

        task  category_id      category_name      AP50
0  diagnosis            0           Impacted  0.793413
1  diagnosis            1             Caries  0.341169
2  diagnosis            2  Periapical Lesion  0.355304
3  diagnosis            3        Deep Caries  0.431300

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!

          task  category_id category_name      AP50
0  enumeration            0             1  0.405941
1  enumeration            1             2  0.168317
2  enumeration            2             3  0.000000
3  enumeration            3             4  0.346181
4  enumeration            4             5  0.261862
5  enumeration            5             6  0.509535
6  enumeration            6             7  0.301391
7  enumeration            7             8  0.706495

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!

       task  category_id category_name      AP50
0  quadrant            0             1  0.491366
1  quadrant            1             2  0.470376
2  quadrant            2             3  0.573466
3  quadrant            3             4  0.598676

                               error_type  count
0                          false_positive    339
1                                 correct    101
2  false_negative_or_localisation_failure     25
3                       enumeration_error     24
4                         diagnosis_error     23
5                    multiple_label_error      6
6                          quadrant_error      3

test A+B+C prediction count: 2680
Saved test unified predictions: /kaggle/working/dentex_final_model_c/predictions/predictions_unified_test.json
Saved test challenge-format predictions: /kaggle/working/dentex_final_model_c/predictions/predictions_challenge_format_test.json
Released-test comparable annotations: 1043
Released-test comparable diagnosis ids: [0, 1, 2]
Released-test prediction coverage: 242 / 250 images
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!

       Subtask        AP      AP50      AP75        AR
0     Quadrant  0.300790  0.506958  0.339354  0.561575
1  Enumeration  0.142426  0.241249  0.158113  0.300694
2    Diagnosis  0.265687  0.460345  0.290705  0.425636
3    Aggregate  0.236301  0.402851  0.262724  0.429302

Bundle created:
/kaggle/working/dentex_final_model_c/download_bundle
/kaggle/working/dentex_final_model_c/download_bundle.zip
Download bundle files:
- final_error_decomposition_validation.csv: 0.02 MB
- final_metrics_released_test_official_style.json: 0.00 MB
- final_metrics_validation_official_style.json: 0.00 MB
- final_per_class_diagnosis_ap50.csv: 0.00 MB
- final_per_class_enumeration_ap50.csv: 0.00 MB
- final_per_class_quadrant_ap50.csv: 0.00 MB
- final_summary.json: 0.00 MB
- pathology_best.pt: 5.24 MB
- predictions_challenge_format_test.json: 0.60 MB
- predictions_challenge_format_validation.json: 0.11 MB
- predictions_unified_test.json: 0.61 MB
- predictions_unified_validation.json: 0.12 MB
- quadrant_best.pt: 18.31 MB
- tooth_best.pt: 5.24 MB
Total bundle size: 30.25 MB

Pruned 8889.57 MB of transient output files.
Removed transient directories/files:
- /kaggle/working/dentex_final_model_c/yolo
- /kaggle/working/dentex_final_model_c/official_eval
- yolo11n.pt
- yolo11s.pt
Saved outputs under: /kaggle/working/dentex_final_model_c/predictions

## 8. Output Summary

In [9]:
summary_path = CFG['pred_root'] / 'final_summary.json'
if summary_path.exists():
    print(json.dumps(json.loads(summary_path.read_text(encoding='utf-8')), indent=2))
else:
    print('Final summary has not been written yet.')

print('Result files:')
for path in sorted(CFG['pred_root'].glob('*')):
    print(f'- {path.name}: {path.stat().st_size / (1024 * 1024):.2f} MB')

{
  "config": {
    "name": "final_model_c_lower_lr_yolo11s_quadrant",
    "pathology_model": "yolo11n.pt",
    "tooth_model": "yolo11n.pt",
    "quadrant_model": "yolo11s.pt",
    "imgsz": 1024,
    "epochs": 500,
    "patience": 30,
    "lr0": 0.003,
    "weight_decay": 0.0005,
    "mosaic": 0.1,
    "scale": 0.15,
    "degrees": 8.0,
    "ab_enable_tta": true,
    "quadrant_enable_tta": false,
    "tooth_assignment_mode": "nearest",
    "quadrant_assignment_mode": "nearest"
  },
  "weights": {
    "pathology": "/kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_pathology/weights/best.pt",
    "tooth": "/kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_tooth/weights/best.pt",
    "quadrant": "/kaggle/working/dentex_final_model_c/runs/final_model_c_lower_lr_yolo11s_quadrant_quadrant/weights/best.pt"
  },
  "validation_metrics": {
    "Quadrant": {
      "AP": 0.33171271667769514,
      "AP50": 0.5334709371868994,
      "AP75": 0.39040796965676927,
      "AR": 0.5631367642395941
    },
    "Enumeration": {
      "AP": 0.19405960880906453,
      "AP50": 0.33746521664129664,
      "AP75": 0.18372715742201332,
      "AR": 0.31697163362952835
    },
    "Diagnosis": {
      "AP": 0.2800266313879377,
      "AP50": 0.48029648268532,
      "AP75": 0.284099652437199,
      "AR": 0.4691989823982398
    },
    "Aggregates": {
      "AP": 0.2685996522915658,
      "AP50": 0.4504108788378387,
      "AP75": 0.2860782598386605,
      "AR": 0.44976912675578745
    }
  },
  "released_test_metrics": {
    "Quadrant": {
      "AP": 0.3007896209535872,
      "AP50": 0.5069578867513952,
      "AP75": 0.339353580535496,
      "AR": 0.5615753121211072
    },
    "Enumeration": {
      "AP": 0.14242640066321874,
      "AP50": 0.24124893517254367,
      "AP75": 0.15811314823636063,
      "AR": 0.30069422923821015
    },
    "Diagnosis": {
      "AP": 0.26568731441208104,
      "AP50": 0.4603450585067781,
      "AP75": 0.2907051481695419,
      "AR": 0.42563593741481764
    },
    "Aggregates": {
      "AP": 0.236301112009629,
      "AP50": 0.402850626810239,
      "AP75": 0.2627239589804662,
      "AR": 0.42930182625804497
    }
  },
  "prediction_files": {
    "validation_unified": "/kaggle/working/dentex_final_model_c/predictions/predictions_unified_validation.json",
    "validation_challenge": "/kaggle/working/dentex_final_model_c/predictions/predictions_challenge_format_validation.json",
    "test_unified": "/kaggle/working/dentex_final_model_c/predictions/predictions_unified_test.json",
    "test_challenge": "/kaggle/working/dentex_final_model_c/predictions/predictions_challenge_format_test.json"
  }
}
Result files:
- final_error_decomposition_validation.csv: 0.02 MB
- final_metrics_released_test_official_style.json: 0.00 MB
- final_metrics_validation_official_style.json: 0.00 MB
- final_per_class_diagnosis_ap50.csv: 0.00 MB
- final_per_class_enumeration_ap50.csv: 0.00 MB
- final_per_class_quadrant_ap50.csv: 0.00 MB
- final_summary.json: 0.00 MB
- predictions_challenge_format_test.json: 0.60 MB
- predictions_challenge_format_validation.json: 0.11 MB
- predictions_unified_test.json: 0.61 MB
- predictions_unified_validation.json: 0.12 MB